from __future__ import annotations

from typing import Any

def detect_charuco(image, *, chess_cfg=None, params, pre_blur_sigma_px=None) -> dict[str, Any]: ...
def detect_chessboard(image, *, chess_cfg=None, params=None, pre_blur_sigma_px=None) -> dict[str, Any] | None: ...
def detect_chessboard_all(image, *, chess_cfg=None, params=None, pre_blur_sigma_px=None) -> Any: ...
def detect_chessboard_debug(image, *, chess_cfg=None, params=None, pre_blur_sigma_px=None) -> Any: ...
def trace_chessboard_topological(image, *, chess_cfg=None, params=None, pre_blur_sigma_px=None) -> Any: ...
def detect_marker_board(image, *, chess_cfg=None, params=None, pre_blur_sigma_px=None) -> dict[str, Any] | None: ...
def detect_puzzleboard(image, *, chess_cfg=None, params, pre_blur_sigma_px=None) -> dict[str, Any]: ...
def detect_chessboard_best(image, configs) -> Any: ...
def detect_charuco_best(image, configs) -> Any: ...
def detect_marker_board_best(image, configs) -> Any: ...
def detect_puzzleboard_best(image, configs) -> dict[str, Any]: ...
def default_puzzleboard_params(rows, cols) -> dict[str, Any]: ...
def render_target_bundle(document) -> dict[str, Any]: ...
def write_target_bundle(document, output_stem) -> dict[str, Any]: ...
