from __future__ import annotations

from typing import Any

def detect_charuco(image, *, chess_cfg=None, params) -> dict[str, Any]: ...
def detect_charuco_with_corners(image, corners, *, params) -> Any: ...
def detect_chessboard(image, *, chess_cfg=None, params=None) -> dict[str, Any] | None: ...
def detect_chessboard_all(image, *, chess_cfg=None, params=None) -> Any: ...
def trace_chessboard_topological(image, *, chess_cfg=None, params=None) -> Any: ...
def detect_marker_board(image, *, chess_cfg=None, params=None) -> dict[str, Any] | None: ...
def detect_marker_board_with_corners(image, corners, *, params=None) -> Any: ...
def detect_puzzleboard(image, *, chess_cfg=None, params) -> dict[str, Any]: ...
def detect_puzzleboard_with_corners(image, corners, *, params) -> Any: ...
def diagnose_charuco(image, *, chess_cfg=None, params) -> Any: ...
def diagnose_charuco_with_corners(image, corners, *, params) -> Any: ...
def diagnose_marker_board(image, *, chess_cfg=None, params=None) -> Any: ...
def diagnose_marker_board_with_corners(image, corners, *, params=None) -> Any: ...
def diagnose_puzzleboard(image, *, chess_cfg=None, params) -> Any: ...
def diagnose_puzzleboard_with_corners(image, corners, *, params) -> Any: ...
def detect_chessboard_best(image, configs, *, chess_cfg=None) -> Any: ...
def detect_charuco_best(image, configs) -> Any: ...
def detect_marker_board_best(image, configs) -> Any: ...
def detect_puzzleboard_best(image, configs) -> dict[str, Any]: ...
def chessboard_sweep_default() -> list[dict[str, Any]]: ...
def charuco_sweep_for_board(board) -> list[dict[str, Any]]: ...
def marker_board_sweep_for_board(board) -> list[dict[str, Any]]: ...
def puzzleboard_sweep_for_board(board) -> list[dict[str, Any]]: ...
def default_puzzleboard_params(rows, cols) -> dict[str, Any]: ...
def render_target_bundle(document) -> dict[str, Any]: ...
def write_target_bundle(document, output_stem) -> dict[str, Any]: ...
