from __future__ import annotations

from typing import Any

def detect_charuco(image, *, chess_cfg=None, params) -> dict[str, Any]: ...
def detect_chessboard(image, *, chess_cfg=None, params=None) -> dict[str, Any] | None: ...
def detect_marker_board(image, *, chess_cfg=None, params=None) -> dict[str, Any] | None: ...
def render_target_bundle(document) -> dict[str, Any]: ...
def write_target_bundle(document, output_stem) -> dict[str, Any]: ...
