// Single-screen workspace: interactive viewport (center) + tabbed right panel
// (Detect / Generate). No backend — all detection runs synchronously in WASM.
//
// Image sources (in priority order):
//   1. User file upload
//   2. Bundled public sample (loaded by URL fetch)
//   3. Synthetic target generated by WASM render_*_png

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import { CanvasViewport, type HitPoint } from "../components/CanvasViewport";
import { LayerToggles } from "../components/LayerToggles";
import { InfoTip } from "../components/InfoTip";
import {
  cornersLayer,
  edgesLayer,
  idsLayer,
  OVERLAY_COLORS,
  rawCornersLayer,
  ringsLayer,
  type OverlayCorner,
} from "../components/overlays";
import { useDebounced } from "../hooks/useDebounced";
import { bitmapFromBytes, useImageBitmapFromUrl } from "../hooks/useImageBitmap";
import {
  charucoSweepForBoard,
  chessboardSweepDefault,
  defaultCharucoParams,
  defaultChessConfig,
  defaultChessboardParams,
  defaultMarkerBoardParams,
  defaultPuzzleBoardParams,
  detectCharuco,
  detectCharucoBest,
  detectChessboard,
  detectChessboardBest,
  detectCorners,
  detectMarkerBoard,
  detectPuzzleBoard,
  detectPuzzleBoardBest,
  listArucoDictionaries,
  puzzleboardSweepForBoard,
  renderCharucoPng,
  renderChessboardPng,
  renderMarkerBoardPng,
  renderPuzzleBoardPng,
  rgbaToGray,
} from "../lib/detector";
import {
  loadImage,
  loadImageFromBytes,
  type ImageData as ImgData,
} from "../lib/image-utils";
import type {
  CharucoParams,
  ChessConfig,
  ChessboardParams,
  DetectionMode,
  MarkerBoardParams,
  PuzzleBoardParams,
} from "../types/calib-targets";

// ---------------------------------------------------------------------------
// Bundled sample gallery
// ---------------------------------------------------------------------------

interface SampleEntry {
  label: string;
  url: string;
  /** The detection mode that matches this sample. */
  mode: DetectionMode;
}

const SAMPLES: SampleEntry[] = [
  { label: "Chessboard", url: "./samples/chessboard.png", mode: "chessboard" },
  { label: "ChArUco",    url: "./samples/charuco.png",    mode: "charuco"    },
  { label: "Marker",     url: "./samples/markerboard.png",mode: "marker_board"},
  { label: "PuzzleBoard",url: "./samples/puzzleboard.png", mode: "puzzleboard"},
];

// ---------------------------------------------------------------------------
// Tooltip data
// ---------------------------------------------------------------------------

interface TooltipData {
  x: number;
  y: number;
  i: number;
  j: number;
  id?: number | null;
  score?: number;
}

// ---------------------------------------------------------------------------
// Helper: extract OverlayCorner[] from any detection result
// ---------------------------------------------------------------------------

function extractOverlayCorners(
  mode: DetectionMode,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  result: any,
): OverlayCorner[] {
  if (!result) return [];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function fromCorner(c: any): OverlayCorner | null {
    if (!c) return null;
    const x = Array.isArray(c.position) ? c.position[0] : c.x;
    const y = Array.isArray(c.position) ? c.position[1] : c.y;
    const i = c.grid?.i ?? 0;
    const j = c.grid?.j ?? 0;
    return { x, y, i, j, id: c.id ?? null, score: c.score };
  }
  if (mode === "corners") {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return (result as any[]).flatMap((c) => {
      const [x, y] = c.position as [number, number];
      return [{ x, y, i: 0, j: 0, id: null }];
    });
  }
  const corners: OverlayCorner[] = [];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const src: any[] = result?.corners ?? [];
  for (const c of src) {
    const oc = fromCorner(c);
    if (oc) corners.push(oc);
  }
  return corners;
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

type Tab = "detect" | "generate";

interface WorkspaceProps {
  ready: boolean;
}

export function Workspace({ ready }: WorkspaceProps) {
  // --- image state ---
  const [imgData, setImgData] = useState<ImgData | null>(null);
  const [bitmap, setBitmap] = useState<ImageBitmap | null>(null);
  const [loadingImg, setLoadingImg] = useState(false);

  // --- sample loading via URL ---
  const [sampleUrl, setSampleUrl] = useState<string | null>(null);
  const sampleBitmap = useImageBitmapFromUrl(sampleUrl);

  // When a sample bitmap loads, also extract its pixel data for WASM
  useEffect(() => {
    if (!sampleBitmap.bitmap || !ready) return;
    const bm = sampleBitmap.bitmap;
    setBitmap(bm);
    // Extract rgba pixels from the bitmap
    const canvas = new OffscreenCanvas(bm.width, bm.height);
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    ctx.drawImage(bm, 0, 0);
    const raw = ctx.getImageData(0, 0, bm.width, bm.height);
    const rgba = new Uint8Array(raw.data);
    const gray = rgbaToGray(rgba, bm.width, bm.height);
    setImgData({ rgba, gray, width: bm.width, height: bm.height });
  }, [sampleBitmap.bitmap, ready]);

  // --- detection mode + config ---
  const [tab, setTab] = useState<Tab>("detect");
  const [mode, setMode] = useState<DetectionMode>("chessboard");
  const [useSweep, setUseSweep] = useState(false);

  // Params (seeded from WASM defaults once ready)
  const [chessCfg, setChessCfg] = useState<ChessConfig | null>(null);
  const [cbParams, setCbParams] = useState<ChessboardParams | null>(null);
  const [charucoParams, setCharucoParams] = useState<CharucoParams | null>(null);
  const [markerParams, setMarkerParams] = useState<MarkerBoardParams | null>(null);
  const [puzzleParams, setPuzzleParams] = useState<PuzzleBoardParams | null>(null);

  useEffect(() => {
    if (!ready) return;
    setChessCfg(defaultChessConfig());
    setCbParams(defaultChessboardParams());
    setCharucoParams(defaultCharucoParams(5, 7, 0.75, "DICT_4X4_50"));
    setMarkerParams(defaultMarkerBoardParams());
    setPuzzleParams(defaultPuzzleBoardParams(10, 10));
  }, [ready]);

  // Debounce params so rapid slider drags don't hammer WASM
  const debouncedCbParams = useDebounced(cbParams, 300);
  const debouncedCharucoParams = useDebounced(charucoParams, 300);
  const debouncedMarkerParams = useDebounced(markerParams, 300);
  const debouncedPuzzleParams = useDebounced(puzzleParams, 300);

  // --- detection output ---
  const [detecting, setDetecting] = useState(false);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const [detectionResult, setDetectionResult] = useState<any>(null);
  const [detectionError, setDetectionError] = useState<string | null>(null);
  const [detectionMode, setDetectionMode] = useState<DetectionMode | null>(null);
  const [timeMs, setTimeMs] = useState<number | null>(null);

  // --- layer visibility ---
  const [visible, setVisible] = useState<Record<string, boolean>>({
    edges: true,
    corners: true,
    rings: true,
    ids: false,
  });

  // --- synthetic generation state (Generate tab) ---
  const [synthKind, setSynthKind] = useState<"chessboard" | "charuco" | "marker_board" | "puzzleboard">("chessboard");
  const [synthRows, setSynthRows] = useState(8);
  const [synthCols, setSynthCols] = useState(10);
  const [synthDict, setSynthDict] = useState("DICT_4X4_50");
  const [synthMarkerRel, setSynthMarkerRel] = useState(0.75);
  const [synthesising, setSynthesising] = useState(false);
  const [synthError, setSynthError] = useState<string | null>(null);
  const dicts = useMemo(() => (ready ? listArucoDictionaries() : []), [ready]);

  // File upload ref
  const fileInputRef = useRef<HTMLInputElement>(null);

  // --- helpers ---

  const loadBitmapFromImgData = useCallback(async (data: ImgData) => {
    const blob = new Blob([data.rgba.slice().buffer as ArrayBuffer]);
    // Create ImageBitmap from rgba via OffscreenCanvas
    const canvas = new OffscreenCanvas(data.width, data.height);
    const ctx = canvas.getContext("2d");
    if (ctx) {
      const id = new globalThis.ImageData(
        new Uint8ClampedArray(data.rgba),
        data.width,
        data.height,
      );
      ctx.putImageData(id, 0, 0);
      const bm = await createImageBitmap(canvas);
      return bm;
    }
    // fallback via blob
    const b = new Blob([blob]);
    return createImageBitmap(b);
  }, []);

  const handleFile = useCallback(
    async (file: File) => {
      setLoadingImg(true);
      setSampleUrl(null);
      try {
        const data = await loadImage(file, rgbaToGray);
        setImgData(data);
        const bm = await loadBitmapFromImgData(data);
        setBitmap(bm);
        setDetectionResult(null);
        setDetectionError(null);
        setTimeMs(null);
        setDetectionMode(null);
      } catch (e: unknown) {
        console.error(e);
      } finally {
        setLoadingImg(false);
      }
    },
    [loadBitmapFromImgData],
  );

  const handleSampleClick = useCallback(
    (entry: SampleEntry) => {
      setSampleUrl(entry.url);
      setMode(entry.mode);
      setDetectionResult(null);
      setDetectionError(null);
      setTimeMs(null);
      setDetectionMode(null);
    },
    [],
  );

  const handleGenerate = useCallback(async () => {
    if (!ready) return;
    setSynthError(null);
    setSynthesising(true);
    try {
      let bytes: Uint8Array;
      const DPI = 300;
      const MM = 12;
      switch (synthKind) {
        case "chessboard":
          bytes = renderChessboardPng(synthRows, synthCols, MM, DPI);
          break;
        case "charuco":
          bytes = renderCharucoPng(synthRows, synthCols, MM, synthMarkerRel, synthDict, DPI);
          break;
        case "marker_board":
          bytes = renderMarkerBoardPng(synthRows, synthCols, MM, DPI);
          break;
        case "puzzleboard":
          bytes = renderPuzzleBoardPng(synthRows, synthCols, MM, DPI);
          break;
      }
      const data = await loadImageFromBytes(bytes, "image/png", rgbaToGray);
      setImgData(data);
      const bm = await bitmapFromBytes(bytes);
      setBitmap(bm);
      setSampleUrl(null);
      // Sync detector to the generated target
      setMode(synthKind);
      if (synthKind === "charuco") {
        setCharucoParams(defaultCharucoParams(synthRows, synthCols, synthMarkerRel, synthDict));
      } else if (synthKind === "puzzleboard") {
        setPuzzleParams(defaultPuzzleBoardParams(synthRows, synthCols));
      }
      setDetectionResult(null);
      setDetectionError(null);
      setTimeMs(null);
      setDetectionMode(null);
      // Auto-switch to detect tab
      setTab("detect");
    } catch (e: unknown) {
      setSynthError(e instanceof Error ? e.message : String(e));
    } finally {
      setSynthesising(false);
    }
  }, [ready, synthKind, synthRows, synthCols, synthDict, synthMarkerRel]);

  // --- run detection ---
  const handleDetect = useCallback(() => {
    if (!imgData || !chessCfg || !debouncedCbParams || !debouncedCharucoParams || !debouncedMarkerParams || !debouncedPuzzleParams) return;
    setDetecting(true);
    setDetectionError(null);
    // setTimeout so the "detecting…" state renders before WASM blocks the thread
    setTimeout(() => {
      try {
        const t0 = performance.now();
        const { gray, width, height } = imgData;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        let res: any;
        switch (mode) {
          case "corners":
            res = detectCorners(gray, width, height, chessCfg);
            break;
          case "chessboard":
            res = useSweep
              ? detectChessboardBest(gray, width, height, chessCfg, chessboardSweepDefault())
              : detectChessboard(gray, width, height, chessCfg, debouncedCbParams);
            break;
          case "charuco":
            res = useSweep
              ? detectCharucoBest(gray, width, height, charucoSweepForBoard(
                  debouncedCharucoParams.board.rows,
                  debouncedCharucoParams.board.cols,
                  debouncedCharucoParams.board.marker_size_rel,
                  debouncedCharucoParams.board.dictionary,
                ))
              : detectCharuco(gray, width, height, chessCfg, debouncedCharucoParams);
            break;
          case "marker_board":
            res = detectMarkerBoard(gray, width, height, chessCfg, debouncedMarkerParams);
            break;
          case "puzzleboard":
            res = useSweep
              ? detectPuzzleBoardBest(gray, width, height, puzzleboardSweepForBoard(
                  debouncedPuzzleParams.board.rows,
                  debouncedPuzzleParams.board.cols,
                ))
              : detectPuzzleBoard(gray, width, height, chessCfg, debouncedPuzzleParams);
            break;
        }
        setDetectionResult(res);
        setDetectionMode(mode);
        setTimeMs(performance.now() - t0);
      } catch (e: unknown) {
        setDetectionError(e instanceof Error ? e.message : String(e));
        setDetectionResult(null);
      } finally {
        setDetecting(false);
      }
    }, 0);
  }, [
    imgData, chessCfg, mode, useSweep,
    debouncedCbParams, debouncedCharucoParams, debouncedMarkerParams, debouncedPuzzleParams,
  ]);

  // --- build overlay layers ---
  const overlayCorners = useMemo<OverlayCorner[]>(() => {
    if (!detectionResult || !detectionMode) return [];
    if (detectionMode === "corners") {
      // raw corners: no grid labels, use position[0/1]
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      return (detectionResult as any[]).map((c: any) => ({
        x: c.position[0] as number,
        y: c.position[1] as number,
        i: 0, j: 0,
      }));
    }
    return extractOverlayCorners(detectionMode, detectionResult);
  }, [detectionResult, detectionMode]);

  const rawCornersForLayer = useMemo(() => {
    if (detectionMode !== "corners" || !detectionResult) return [];
    return detectionResult as Array<{ position: [number, number]; axes: Array<{ angle: number }>; strength: number }>;
  }, [detectionMode, detectionResult]);

  const layers = useMemo(() => {
    if (detectionMode === "corners") {
      return [rawCornersLayer(rawCornersForLayer, visible["corners"] ?? true)];
    }
    return [
      edgesLayer(overlayCorners, visible["edges"] ?? true),
      cornersLayer(overlayCorners, visible["corners"] ?? true),
      ringsLayer(overlayCorners, visible["rings"] ?? true),
      idsLayer(overlayCorners, visible["ids"] ?? false),
    ];
  }, [overlayCorners, rawCornersForLayer, detectionMode, visible]);

  const hitPoints = useMemo<HitPoint<TooltipData>[]>(() => {
    return overlayCorners.map((c) => ({
      x: c.x,
      y: c.y,
      data: { x: c.x, y: c.y, i: c.i, j: c.j, id: c.id, score: c.score },
    }));
  }, [overlayCorners]);

  // --- stats derived from result ---
  const cornerCount = overlayCorners.length;
  const markerCount = useMemo(() => {
    if (detectionMode !== "charuco" || !detectionResult) return null;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return (detectionResult as any)?.markers?.length ?? null;
  }, [detectionMode, detectionResult]);

  // --- drop zone state ---
  const [draggingOver, setDraggingOver] = useState(false);

  return (
    <div
      style={{
        display: "flex",
        height: "100%",
        overflow: "hidden",
      }}
    >
      {/* ------------------------------------------------------------------ */}
      {/* Viewport                                                            */}
      {/* ------------------------------------------------------------------ */}
      <div
        style={{ flex: 1, minWidth: 0, position: "relative" }}
        onDrop={(e) => {
          e.preventDefault();
          setDraggingOver(false);
          const file = e.dataTransfer.files[0];
          if (file) void handleFile(file);
        }}
        onDragOver={(e) => { e.preventDefault(); setDraggingOver(true); }}
        onDragLeave={() => setDraggingOver(false)}
      >
        <CanvasViewport
          image={bitmap}
          layers={layers}
          hitPoints={hitPoints}
          renderTooltip={(d) => (
            <>
              <div style={{ color: "var(--text)" }}>
                {d.id != null ? (
                  <>id {d.id} <span style={{ color: "var(--text-muted)" }}>· ({d.i}, {d.j})</span></>
                ) : (
                  <>({d.i}, {d.j})</>
                )}
              </div>
              <div style={{ color: "var(--text-muted)" }}>
                x {d.x.toFixed(1)} · y {d.y.toFixed(1)}
                {d.score != null && <> · score {d.score.toFixed(1)}</>}
              </div>
            </>
          )}
        />
        {/* Drag overlay */}
        {draggingOver && (
          <div
            style={{
              position: "absolute",
              inset: 0,
              background: "color-mix(in srgb, var(--bg0) 85%, transparent)",
              border: "2px dashed var(--accent)",
              borderRadius: "var(--radius)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              pointerEvents: "none",
              fontSize: 15,
              color: "var(--accent)",
            }}
          >
            Drop image to load
          </div>
        )}
        {(sampleBitmap.loading || loadingImg) && (
          <div style={{
            position: "absolute", inset: 0,
            display: "flex", alignItems: "center", justifyContent: "center",
            background: "color-mix(in srgb, var(--bg0) 70%, transparent)",
            color: "var(--text-muted)", fontSize: 13,
          }}>
            Loading…
          </div>
        )}
      </div>

      {/* ------------------------------------------------------------------ */}
      {/* Right panel                                                         */}
      {/* ------------------------------------------------------------------ */}
      <aside
        style={{
          width: 300,
          flexShrink: 0,
          borderLeft: "1px solid var(--border)",
          background: "var(--bg1)",
          overflowY: "auto",
          display: "flex",
          flexDirection: "column",
        }}
      >
        {/* Tab bar */}
        <div style={{
          display: "flex",
          borderBottom: "1px solid var(--border)",
          flexShrink: 0,
        }}>
          {(["detect", "generate"] as Tab[]).map((t) => (
            <button
              key={t}
              onClick={() => setTab(t)}
              style={{
                flex: 1,
                padding: "10px 0",
                background: "transparent",
                border: "none",
                borderBottom: tab === t ? "2px solid var(--accent)" : "2px solid transparent",
                color: tab === t ? "var(--text)" : "var(--text-muted)",
                cursor: "pointer",
                fontSize: 12,
                fontWeight: tab === t ? 600 : 400,
                letterSpacing: "0.02em",
              }}
            >
              {(t[0] ?? "").toUpperCase() + t.slice(1)}
            </button>
          ))}
        </div>

        {/* Panel body */}
        <div style={{ flex: 1, overflowY: "auto", padding: "var(--s4)", display: "flex", flexDirection: "column", gap: "var(--s4)" }}>
          {tab === "detect" && (
            <DetectPanel
              ready={ready}
              imgData={imgData}
              mode={mode}
              setMode={setMode}
              useSweep={useSweep}
              setUseSweep={setUseSweep}
              cbParams={cbParams}
              setCbParams={setCbParams}
              charucoParams={charucoParams}
              setCharucoParams={setCharucoParams}
              markerParams={markerParams}
              setMarkerParams={setMarkerParams}
              puzzleParams={puzzleParams}
              setPuzzleParams={setPuzzleParams}
              detecting={detecting}
              onDetect={handleDetect}
              detectionResult={detectionResult}
              detectionMode={detectionMode}
              detectionError={detectionError}
              cornerCount={cornerCount}
              markerCount={markerCount}
              timeMs={timeMs}
              visible={visible}
              setVisible={setVisible}
              onFileClick={() => fileInputRef.current?.click()}
              samples={SAMPLES}
              onSampleClick={handleSampleClick}
            />
          )}
          {tab === "generate" && (
            <GeneratePanel
              ready={ready}
              synthKind={synthKind}
              setSynthKind={setSynthKind}
              synthRows={synthRows}
              setSynthRows={setSynthRows}
              synthCols={synthCols}
              setSynthCols={setSynthCols}
              synthDict={synthDict}
              setSynthDict={setSynthDict}
              synthMarkerRel={synthMarkerRel}
              setSynthMarkerRel={setSynthMarkerRel}
              synthesising={synthesising}
              synthError={synthError}
              onGenerate={handleGenerate}
              dicts={dicts}
            />
          )}
        </div>
      </aside>

      {/* Hidden file input */}
      <input
        ref={fileInputRef}
        type="file"
        accept="image/*"
        style={{ display: "none" }}
        onChange={(e) => {
          const file = e.target.files?.[0];
          if (file) void handleFile(file);
          e.target.value = "";
        }}
      />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Detect panel
// ---------------------------------------------------------------------------

function DetectPanel({
  ready,
  imgData,
  mode, setMode,
  useSweep, setUseSweep,
  cbParams, setCbParams,
  charucoParams, setCharucoParams,
  markerParams, setMarkerParams,
  puzzleParams, setPuzzleParams,
  detecting,
  onDetect,
  detectionResult,
  detectionMode,
  detectionError,
  cornerCount,
  markerCount,
  timeMs,
  visible, setVisible,
  onFileClick,
  samples,
  onSampleClick,
}: {
  ready: boolean;
  imgData: ImgData | null;
  mode: DetectionMode;
  setMode: (m: DetectionMode) => void;
  useSweep: boolean;
  setUseSweep: (v: boolean) => void;
  cbParams: ChessboardParams | null;
  setCbParams: (p: ChessboardParams) => void;
  charucoParams: CharucoParams | null;
  setCharucoParams: (p: CharucoParams) => void;
  markerParams: MarkerBoardParams | null;
  setMarkerParams: (p: MarkerBoardParams) => void;
  puzzleParams: PuzzleBoardParams | null;
  setPuzzleParams: (p: PuzzleBoardParams) => void;
  detecting: boolean;
  onDetect: () => void;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  detectionResult: any;
  detectionMode: DetectionMode | null;
  detectionError: string | null;
  cornerCount: number;
  markerCount: number | null;
  timeMs: number | null;
  visible: Record<string, boolean>;
  setVisible: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  onFileClick: () => void;
  samples: SampleEntry[];
  onSampleClick: (s: SampleEntry) => void;
}) {
  const hasImage = imgData != null;

  // The three "Detection params" knobs (min strength / min labels / max comps)
  // live on a `ChessboardParams`, but every non-chessboard family nests its own
  // copy under `params.chessboard` and `handleDetect` passes THAT, not `cbParams`.
  // Route the control to whichever sub-config the active family actually uses so
  // the tuning is never a silent no-op.
  const sharedChess: ChessboardParams | null =
    mode === "chessboard" ? cbParams
    : mode === "charuco" ? charucoParams?.chessboard ?? null
    : mode === "marker_board" ? markerParams?.chessboard ?? null
    : mode === "puzzleboard" ? puzzleParams?.chessboard ?? null
    : null;

  const setSharedChess = (next: ChessboardParams) => {
    switch (mode) {
      case "chessboard":
        setCbParams(next);
        break;
      case "charuco":
        if (charucoParams) setCharucoParams({ ...charucoParams, chessboard: next });
        break;
      case "marker_board":
        if (markerParams) setMarkerParams({ ...markerParams, chessboard: next });
        break;
      case "puzzleboard":
        if (puzzleParams) setPuzzleParams({ ...puzzleParams, chessboard: next });
        break;
    }
  };

  return (
    <>
      {/* Image source */}
      <div>
        <div className="label" style={{ marginBottom: "var(--s2)" }}>Image</div>
        <div style={{ display: "flex", flexDirection: "column", gap: "var(--s2)" }}>
          <button className="btn" onClick={onFileClick} style={{ width: "100%", justifyContent: "center" }}>
            Upload file…
          </button>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "var(--s1)" }}>
            {samples.map((s) => (
              <button
                key={s.url}
                className="btn"
                style={{ fontSize: 11, padding: "4px 8px", justifyContent: "center" }}
                onClick={() => onSampleClick(s)}
              >
                {s.label}
              </button>
            ))}
          </div>
          {imgData && (
            <div style={{ fontSize: 11, color: "var(--text-muted)" }}>
              {imgData.width} × {imgData.height} px
            </div>
          )}
        </div>
      </div>

      {/* Stats chips */}
      {(detectionResult != null || detectionError) && (
        <div style={{ display: "flex", flexWrap: "wrap", gap: "var(--s1)" }}>
          {detectionError ? (
            <span className="chip err">{detectionError}</span>
          ) : (
            <>
              <span className="chip">{cornerCount} corners</span>
              {markerCount != null && <span className="chip">{markerCount} markers</span>}
              {timeMs != null && (
                <span className="chip">{timeMs.toFixed(1)} ms</span>
              )}
              {detectionMode === "chessboard" && detectionResult == null && (
                <span className="chip err">no detection</span>
              )}
            </>
          )}
        </div>
      )}

      {/* Target family */}
      <div>
        <div className="label" style={{ marginBottom: "var(--s2)" }}>Target</div>
        <SelectRow
          label="Family"
          value={mode}
          options={[
            ["corners", "Corners"],
            ["chessboard", "Chessboard"],
            ["charuco", "ChArUco"],
            ["marker_board", "Marker board"],
            ["puzzleboard", "PuzzleBoard"],
          ]}
          onChange={(v) => setMode(v as DetectionMode)}
        />
      </div>

      {/* Board geometry (family-specific) */}
      {mode === "charuco" && charucoParams && (
        <BoardGeometry
          title="Board geometry"
          rows={charucoParams.board.rows}
          cols={charucoParams.board.cols}
          onRows={(v) => setCharucoParams({ ...charucoParams, board: { ...charucoParams.board, rows: v } })}
          onCols={(v) => setCharucoParams({ ...charucoParams, board: { ...charucoParams.board, cols: v } })}
          extra={
            <SelectRow
              label="Dictionary"
              value={charucoParams.board.dictionary}
              options={charucoParams ? [] : []}
              dynamicOptions={ready ? listArucoDictionaries().map(d => [d, d] as [string, string]) : []}
              onChange={(v) => setCharucoParams({ ...charucoParams, board: { ...charucoParams.board, dictionary: v } })}
            />
          }
        />
      )}
      {mode === "marker_board" && markerParams && (
        <BoardGeometry
          title="Board geometry"
          rows={markerParams.layout.rows}
          cols={markerParams.layout.cols}
          onRows={(v) => setMarkerParams({ ...markerParams, layout: { ...markerParams.layout, rows: v } })}
          onCols={(v) => setMarkerParams({ ...markerParams, layout: { ...markerParams.layout, cols: v } })}
        />
      )}
      {mode === "puzzleboard" && puzzleParams && (
        <BoardGeometry
          title="Board geometry"
          rows={puzzleParams.board.rows}
          cols={puzzleParams.board.cols}
          onRows={(v) => setPuzzleParams({ ...puzzleParams, board: { ...puzzleParams.board, rows: v } })}
          onCols={(v) => setPuzzleParams({ ...puzzleParams, board: { ...puzzleParams.board, cols: v } })}
        />
      )}

      {/* Core params */}
      {mode !== "corners" && sharedChess && (
        <div>
          <div className="label" style={{ marginBottom: "var(--s2)" }}>
            Detection params
            <InfoTip text="These three knobs tune the corner + grid stage shared by every detector family. Adjust if the detector misses corners on unusual images." />
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: "var(--s2)" }}>
            <NumberRow
              label="Min strength"
              value={sharedChess.min_corner_strength}
              step={0.05}
              onChange={(v) => setSharedChess({ ...sharedChess, min_corner_strength: v })}
            />
            <NumberRow
              label="Min labels"
              value={sharedChess.min_labeled_corners}
              step={1}
              integer
              onChange={(v) => setSharedChess({ ...sharedChess, min_labeled_corners: v })}
            />
            <NumberRow
              label="Max comps"
              value={sharedChess.max_components}
              step={1}
              integer
              onChange={(v) => setSharedChess({ ...sharedChess, max_components: v })}
            />
          </div>
        </div>
      )}

      {/* Sweep toggle */}
      {mode !== "corners" && mode !== "marker_board" && (
        <label
          style={{
            display: "flex",
            alignItems: "center",
            gap: 8,
            fontSize: 12,
            cursor: "pointer",
            color: "var(--text-muted)",
          }}
        >
          <input
            type="checkbox"
            checked={useSweep}
            onChange={(e) => setUseSweep(e.target.checked)}
            style={{ accentColor: "var(--accent)" }}
          />
          Multi-config sweep (detect_*_best)
          <InfoTip text="Runs the built-in 3-config preset and keeps the best result. Slower but more robust." />
        </label>
      )}

      {/* Detect button */}
      <button
        className="btn primary"
        disabled={!hasImage || !ready || detecting}
        onClick={onDetect}
        style={{ width: "100%", justifyContent: "center", padding: "8px 12px" }}
      >
        {detecting ? "Detecting…" : "Detect"}
      </button>

      {/* Layer toggles */}
      {detectionResult != null && detectionMode !== "corners" && (
        <div>
          <div className="label" style={{ marginBottom: "var(--s2)" }}>Layers</div>
          <LayerToggles
            toggles={[
              { id: "edges", label: "Grid edges", checked: visible["edges"] ?? true, swatch: OVERLAY_COLORS.edge },
              { id: "corners", label: "Corners", checked: visible["corners"] ?? true, swatch: OVERLAY_COLORS.corner },
              { id: "rings", label: "Origin / far rings", checked: visible["rings"] ?? true, swatch: OVERLAY_COLORS.origin },
              { id: "ids", label: "(i, j) labels · zoom ≥ 2×", checked: visible["ids"] ?? false },
            ]}
            onChange={(id, checked) => setVisible((v) => ({ ...v, [id]: checked }))}
          />
        </div>
      )}
    </>
  );
}

// ---------------------------------------------------------------------------
// Generate panel
// ---------------------------------------------------------------------------

function GeneratePanel({
  ready,
  synthKind, setSynthKind,
  synthRows, setSynthRows,
  synthCols, setSynthCols,
  synthDict, setSynthDict,
  synthMarkerRel, setSynthMarkerRel,
  synthesising, synthError,
  onGenerate, dicts,
}: {
  ready: boolean;
  synthKind: "chessboard" | "charuco" | "marker_board" | "puzzleboard";
  setSynthKind: (v: "chessboard" | "charuco" | "marker_board" | "puzzleboard") => void;
  synthRows: number;
  setSynthRows: (v: number) => void;
  synthCols: number;
  setSynthCols: (v: number) => void;
  synthDict: string;
  setSynthDict: (v: string) => void;
  synthMarkerRel: number;
  setSynthMarkerRel: (v: number) => void;
  synthesising: boolean;
  synthError: string | null;
  onGenerate: () => void;
  dicts: string[];
}) {
  return (
    <>
      <div>
        <div style={{ fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5, marginBottom: "var(--s3)" }}>
          Render a synthetic calibration target using WASM, load it into the viewport, and auto-configure the matching detector.
        </div>
      </div>
      <div>
        <div className="label" style={{ marginBottom: "var(--s2)" }}>Target type</div>
        <SelectRow
          label="Kind"
          value={synthKind}
          options={[
            ["chessboard", "Chessboard"],
            ["charuco", "ChArUco"],
            ["marker_board", "Marker board"],
            ["puzzleboard", "PuzzleBoard"],
          ]}
          onChange={(v) => setSynthKind(v as typeof synthKind)}
        />
      </div>

      <div>
        <div className="label" style={{ marginBottom: "var(--s2)" }}>Board size</div>
        <div style={{ display: "flex", flexDirection: "column", gap: "var(--s2)" }}>
          <NumberRow label="Rows" value={synthRows} step={1} integer min={2} max={64} onChange={setSynthRows} />
          <NumberRow label="Cols" value={synthCols} step={1} integer min={2} max={64} onChange={setSynthCols} />
        </div>
      </div>

      {synthKind === "charuco" && (
        <div>
          <div className="label" style={{ marginBottom: "var(--s2)" }}>ChArUco options</div>
          <div style={{ display: "flex", flexDirection: "column", gap: "var(--s2)" }}>
            <SelectRow
              label="Dictionary"
              value={synthDict}
              options={[]}
              dynamicOptions={dicts.map(d => [d, d] as [string, string])}
              onChange={setSynthDict}
            />
            <NumberRow
              label="Marker rel"
              value={synthMarkerRel}
              step={0.05}
              min={0.1}
              max={0.95}
              onChange={setSynthMarkerRel}
            />
          </div>
        </div>
      )}

      <button
        className="btn primary"
        disabled={!ready || synthesising}
        onClick={onGenerate}
        style={{ width: "100%", justifyContent: "center", padding: "8px 12px" }}
      >
        {synthesising ? "Generating…" : "Generate & load"}
      </button>

      {synthError && (
        <div style={{
          padding: "8px 12px",
          background: "color-mix(in srgb, var(--err) 10%, transparent)",
          border: "1px solid color-mix(in srgb, var(--err) 40%, transparent)",
          borderRadius: "var(--radius)",
          color: "var(--err)",
          fontSize: 12,
        }}>
          {synthError}
        </div>
      )}
    </>
  );
}

// ---------------------------------------------------------------------------
// Shared mini-components
// ---------------------------------------------------------------------------

function BoardGeometry({
  title,
  rows, cols,
  onRows, onCols,
  extra,
}: {
  title: string;
  rows: number;
  cols: number;
  onRows: (v: number) => void;
  onCols: (v: number) => void;
  extra?: React.ReactNode;
}) {
  return (
    <div>
      <div className="label" style={{ marginBottom: "var(--s2)" }}>{title}</div>
      <div style={{ display: "flex", flexDirection: "column", gap: "var(--s2)" }}>
        <NumberRow label="Rows" value={rows} step={1} integer min={2} onChange={onRows} />
        <NumberRow label="Cols" value={cols} step={1} integer min={2} onChange={onCols} />
        {extra}
      </div>
    </div>
  );
}

function NumberRow({
  label, value, step, integer, min, max, onChange,
}: {
  label: string;
  value: number;
  step: number;
  integer?: boolean;
  min?: number;
  max?: number;
  onChange: (v: number) => void;
}) {
  return (
    <label style={{
      display: "grid",
      gridTemplateColumns: "90px 1fr",
      alignItems: "center",
      gap: "var(--s2)",
      fontSize: 12,
      color: "var(--text-muted)",
    }}>
      {label}
      <input
        className="input"
        type="number"
        step={step}
        value={value}
        min={min}
        max={max}
        style={{ padding: "3px 6px", fontSize: 12 }}
        onChange={(e) => {
          const v = e.target.valueAsNumber;
          if (!Number.isNaN(v)) onChange(integer ? Math.round(v) : v);
        }}
      />
    </label>
  );
}

function SelectRow({
  label, value, options, dynamicOptions, onChange,
}: {
  label: string;
  value: string;
  options: readonly (readonly [string, string])[];
  dynamicOptions?: readonly (readonly [string, string])[];
  onChange: (v: string) => void;
}) {
  const all = [...options, ...(dynamicOptions ?? [])];
  return (
    <label style={{
      display: "grid",
      gridTemplateColumns: "90px 1fr",
      alignItems: "center",
      gap: "var(--s2)",
      fontSize: 12,
      color: "var(--text-muted)",
    }}>
      {label}
      <select
        className="select"
        value={value}
        onChange={(e) => onChange(e.target.value)}
        style={{ fontSize: 12 }}
      >
        {all.map(([k, l]) => (
          <option key={k} value={k}>{l}</option>
        ))}
      </select>
    </label>
  );
}
