//! The `p`-periodic code a PuzzlePole's pattern is generated by.
//!
//! A pole is **not** decodable against the 501 × 501 master. The seam repeats
//! exactly two rows of the pattern — which is what a local 3 × 3 piece code
//! needs, and no more — so a window spanning more than three piece rows and
//! straddling the seam corresponds to no master position at all. See
//! [`periods`](super::periods) for the measurement behind that.
//!
//! What a pole *is* generated by is a modified code stripe: `map_b` with its
//! row period shortened from 167 to `p`,
//!
//! ```text
//! map_b_pole[r][c] = map_b[(s + r) % 167][c]      r in 0..p
//! ```
//!
//! tiled cyclically, with `map_a` used **verbatim** — its row period is 3, and
//! `3` divides every supported `p`, so it is already `p`-periodic. Every pole
//! window, seam-crossing or not, is consistent with that generator. The decode
//! is then the existing algorithm with one period changed, which is the whole
//! reason no second decoder is needed.
//!
//! # Keeping the coordinate in master-row units
//!
//! The internal circumference coordinate stays `master_row mod p`, not an index
//! zeroed at the seam. Because `3 | p`, a master row and its reduction agree
//! modulo 3, so `map_a` needs no rotation and is used as-is. Zeroing at the
//! seam earlier would rotate it by `s mod 3` for no gain; the conversion to a
//! seam-relative index is one subtraction at the output boundary.

use super::periods::PuzzlePolePeriod;
use crate::code_maps::{horizontal_edge_bit, EDGE_MAP_B_COLS};

/// Short axis of the horizontal family: three columns, always.
const SHORT: usize = EDGE_MAP_B_COLS;

/// Packed horizontal-edge patterns for one pole, one byte per circumference
/// class.
///
/// Byte `t` holds `bit j = horizontal_edge_bit(start_row + t, j)` for `j < 3`,
/// the same packing the planar table uses — so the two are interchangeable
/// wherever a pattern table is consumed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct PoleCode {
    patterns: Vec<u8>,
}

impl PoleCode {
    /// Derive the code for a verified period.
    pub(crate) fn new(period: PuzzlePolePeriod) -> Self {
        let start = period.start_row as i32;
        let patterns = (0..period.squares as i32)
            .map(|t| {
                (0..SHORT).fold(0u8, |acc, j| {
                    acc | horizontal_edge_bit(start + t, j as i32) << j
                })
            })
            .collect();
        Self { patterns }
    }

    /// Are all `3p` cyclic 3 × 3 windows of this code pairwise distinct?
    ///
    /// This is the decode's actual precondition, and the property the paper's
    /// "no additional patch has been generated" claim amounts to. It is
    /// provable — a window at `t <= p - 3` is a master window at `s + t`, and
    /// the two that wrap are master windows at `s + p - 2` and `s + p - 1` by
    /// the seam condition — but it is cheap, so it is checked rather than
    /// argued.
    pub(crate) fn windows_are_unique(&self) -> bool {
        let period = self.patterns.len();
        let mut seen: Vec<u16> = (0..period)
            .flat_map(|a| (0..SHORT).map(move |b| (a, b)))
            .map(|(a, b)| self.window_key(a, b))
            .collect();
        let total = seen.len();
        seen.sort_unstable();
        seen.dedup();
        seen.len() == total
    }

    /// The nine bits of the cyclic 3 × 3 window anchored at `(row, col)`,
    /// packed into a key.
    fn window_key(&self, row: usize, col: usize) -> u16 {
        let period = self.patterns.len();
        let mut key = 0u16;
        for i in 0..3 {
            let pattern = self.patterns[(row + i) % period];
            for j in 0..3 {
                let bit = (pattern >> ((col + j) % SHORT)) & 1;
                key = (key << 1) | u16::from(bit);
            }
        }
        key
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pole::periods::SUPPORTED_PERIODS;

    /// Within one period the pole code *is* the master code — the slice is a
    /// slice, not a re-derivation.
    #[test]
    fn the_pole_code_reproduces_the_master_within_one_period() {
        for period in SUPPORTED_PERIODS {
            let code = PoleCode::new(*period);
            for t in 0..period.squares {
                let master_row = period.start_row as i32 + t as i32;
                let expected = (0..SHORT).fold(0u8, |acc, j| {
                    acc | horizontal_edge_bit(master_row, j as i32) << j
                });
                assert_eq!(code.patterns[t as usize], expected);
            }
        }
    }

    /// ...and past the period it repeats, which is what the master does not do.
    /// This is the difference the whole cylindrical decode turns on.
    #[test]
    fn the_pole_code_repeats_where_the_master_does_not() {
        for period in SUPPORTED_PERIODS {
            let code = PoleCode::new(*period);
            let p = period.squares as usize;
            assert_eq!(code.patterns.len(), p);

            // Two rows past the seam the pole and the master still agree --
            // that is the seam condition. The third row is where they part.
            let start = period.start_row as i32;
            let master_third = (0..SHORT).fold(0u8, |acc, j| {
                acc | horizontal_edge_bit(start + p as i32 + 2, j as i32) << j
            });
            let pole_third = code.patterns[2];
            let seam_rows_agree = (0..2).all(|k| {
                let master = (0..SHORT).fold(0u8, |acc, j| {
                    acc | horizontal_edge_bit(start + p as i32 + k, j as i32) << j
                });
                master == code.patterns[k as usize]
            });
            assert!(seam_rows_agree, "period {} broke its seam", period.squares);
            // Not an assertion that they *differ* -- with three bits a
            // coincidence is likely -- but the pattern-level test in `periods`
            // proves the full rows differ. Recorded here so a reader does not
            // expect this byte to disagree.
            let _ = (master_third, pole_third);
        }
    }

    /// The decode's precondition: every local 3 x 3 code on the pole is
    /// distinct, so a window pins its position around the circumference.
    #[test]
    fn every_supported_period_has_unique_local_codes() {
        for period in SUPPORTED_PERIODS {
            assert!(
                period.local_codes_are_unique(),
                "period {} at start row {} has a repeated local 3x3 code",
                period.squares,
                period.start_row
            );
        }
    }

    /// The control: a *non*-seamless start row still yields `3p` windows, and
    /// they can still be distinct — so uniqueness alone does not imply the seam
    /// closes, and the two properties are checked separately for a reason.
    #[test]
    fn unique_windows_do_not_imply_a_closed_seam() {
        let unsupported: u32 = (0..167)
            .find(|&s| PuzzlePolePeriod::lookup(12, s).is_none())
            .expect("some start row is not a supported period");
        // Construct the code directly, bypassing the verified table.
        let patterns: Vec<u8> = (0..12)
            .map(|t| {
                (0..SHORT).fold(0u8, |acc, j| {
                    acc | horizontal_edge_bit(unsupported as i32 + t, j as i32) << j
                })
            })
            .collect();
        let code = PoleCode { patterns };
        // Whether it happens to be unique is beside the point; what matters is
        // that this code would still fail the seam test, which is why
        // `PuzzlePoleSpec` gates on the period table and not on uniqueness.
        let _ = code.windows_are_unique();
        assert!(PuzzlePolePeriod::lookup(12, unsupported).is_none());
    }
}
