//! The PuzzlePole detector.
//!
//! Structurally the planar pipeline: ChESS corners, chessboard grid assembly,
//! edge-dot sampling, period-3 consensus, then a decode. Every one of those
//! stages is *the same code* — the sampler, the consensus and the class tables
//! are shared, not forked.
//!
//! Three things differ, and only three:
//!
//! 1. **The code.** A pole is generated by `map_b` wrapped at the pole's
//!    circumference rather than at 167, so it decodes against that
//!    ([`super::code`]) and never against the 501 × 501 master.
//! 2. **The origin space.** One axis is a ring. `BoardRect::pole` says so, and
//!    the scan enumerates it directly — a few thousand hypotheses, where the
//!    planar full search has a quarter of a million and needs a CRT collapse
//!    that a pole cannot use anyway.
//! 3. **The window floor.** A pole's two axes carry different codes, so the
//!    floor is a rectangle, and it is checked *after* the decode has fixed
//!    which local axis is which.

use super::code::PoleCode;
use super::error::PuzzlePoleDetectError;
use super::params::{required_edges_rect, required_logical_bits_rect};
use super::{PuzzlePoleCorner, PuzzlePoleDetection, PuzzlePoleParams};
use crate::code_maps::PuzzleBoardObservedEdge;
use crate::detector::consensus::EdgeConsensus;
use crate::detector::decode::{decode_fixed_hard, decode_fixed_soft, BoardRect, CodeGeometry};
use crate::detector::edge_sampling::sample_all_edges;
use crate::detector::{PuzzleBoardDecodeInfo, PuzzleBoardScoringMode};
use calib_targets_chessboard::{ChessCorner, ChessboardDetector};
use calib_targets_core::{GrayImageView, LabeledCorner};

/// Detects PuzzlePole targets.
pub struct PuzzlePoleDetector {
    params: PuzzlePoleParams,
    chessboard: ChessboardDetector,
}

impl PuzzlePoleDetector {
    /// Build a detector for the configured pole.
    pub fn new(params: PuzzlePoleParams) -> Result<Self, PuzzlePoleDetectError> {
        let chessboard = ChessboardDetector::new(params.chessboard.clone())
            .map_err(|_| PuzzlePoleDetectError::ChessboardNotDetected)?;
        Ok(Self { params, chessboard })
    }

    /// The parameters in force.
    #[must_use]
    pub fn params(&self) -> &PuzzlePoleParams {
        &self.params
    }

    /// Detect ChESS corners on an image with this detector's front-end config.
    #[must_use]
    pub fn detect_corners(&self, image: &GrayImageView<'_>) -> Vec<ChessCorner> {
        calib_targets_chessboard::detect_corners(image, &self.params.chess)
    }

    /// Detect a pole in an image.
    pub fn detect(
        &self,
        image: &GrayImageView<'_>,
    ) -> Result<PuzzlePoleDetection, PuzzlePoleDetectError> {
        let corners = self.detect_corners(image);
        self.detect_with_corners(image, &corners)
    }

    /// Detect a pole from an already-computed corner cloud.
    ///
    /// Every grid component is tried, and the best decode wins — a pole seen
    /// obliquely often breaks into more than one component, and the largest is
    /// not always the one that decodes.
    pub fn detect_with_corners(
        &self,
        image: &GrayImageView<'_>,
        corners: &[ChessCorner],
    ) -> Result<PuzzlePoleDetection, PuzzlePoleDetectError> {
        let components = self.chessboard.detect_all(corners);
        if components.is_empty() {
            return Err(PuzzlePoleDetectError::ChessboardNotDetected);
        }

        let mut best: Option<PuzzlePoleDetection> = None;
        let mut last_err = PuzzlePoleDetectError::DecodeFailed;
        for component in &components {
            let labelled: Vec<LabeledCorner> = component
                .corners
                .iter()
                .map(|c| LabeledCorner::new(c.position, c.score).with_grid(c.grid))
                .collect();
            match self.decode_component(image, &labelled) {
                Ok(found) => {
                    let better = best
                        .as_ref()
                        .is_none_or(|b| found.corners.len() > b.corners.len());
                    if better {
                        best = Some(found);
                    }
                }
                Err(err) => last_err = err,
            }
            if !self.params.decode.search_all_components && best.is_some() {
                break;
            }
        }
        best.ok_or(last_err)
    }

    /// Decode one grid component.
    fn decode_component(
        &self,
        image: &GrayImageView<'_>,
        labelled: &[LabeledCorner],
    ) -> Result<PuzzlePoleDetection, PuzzlePoleDetectError> {
        let cfg = &self.params.decode;
        let spec = &self.params.pole;
        let inliers: Vec<usize> = (0..labelled.len()).collect();
        let observed = sample_all_edges(image, labelled, &inliers, cfg.sample_radius_rel);

        // The dot floor for the *smallest* window that could decode. It is a
        // cheap rejection; the real check is the per-axis one after the decode.
        let min_edges = required_edges_rect(cfg.min_circumference_span, cfg.min_axial_span);
        if observed.len() < min_edges {
            return Err(PuzzlePoleDetectError::NotEnoughEdges {
                observed: observed.len(),
                needed: min_edges,
            });
        }
        let filtered: Vec<PuzzleBoardObservedEdge> = observed
            .iter()
            .copied()
            .filter(|e| e.confidence >= cfg.min_bit_confidence)
            .collect();
        if filtered.len() < min_edges {
            return Err(PuzzlePoleDetectError::NotEnoughEdges {
                observed: filtered.len(),
                needed: min_edges,
            });
        }

        let consensus = EdgeConsensus::build(&filtered);
        let logical = if cfg.effective_tuning().edge_consensus {
            consensus.class_observations()
        } else {
            filtered.clone()
        };
        let needed_bits =
            required_logical_bits_rect(cfg.min_circumference_span, cfg.min_axial_span);
        if logical.len() < needed_bits {
            return Err(PuzzlePoleDetectError::NotEnoughLogicalBits {
                determined: logical.len(),
                needed: needed_bits,
            });
        }

        let code = PoleCode::new(spec.period());
        let geometry = CodeGeometry::pole(code.patterns());
        let board = BoardRect::pole(
            spec.circumference_squares,
            spec.axial_start_col,
            spec.axial_squares,
        );
        let transforms = cfg.symmetry_mode.transforms();
        let soft = super::params::soft_cfg_from(cfg);
        let decoded = match cfg.scoring_mode {
            PuzzleBoardScoringMode::HardWeighted => decode_fixed_hard(
                &logical,
                &filtered,
                geometry,
                board,
                transforms,
                cfg.max_bit_error_rate,
            ),
            PuzzleBoardScoringMode::SoftLogLikelihood => decode_fixed_soft(
                &filtered,
                &logical,
                geometry,
                board,
                transforms,
                &soft,
                cfg.max_bit_error_rate,
            ),
        };
        let decoded = decoded.ok_or(PuzzlePoleDetectError::DecodeFailed)?;

        // Map each labelled corner onto the pole. The decode has fixed which
        // local axis is which, so from here the indices are unambiguous.
        let period = spec.circumference_squares as i32;
        let mut out: Vec<PuzzlePoleCorner> = Vec::with_capacity(labelled.len());
        for lc in labelled {
            let Some(grid) = lc.grid else { continue };
            let master = decoded.alignment.apply(grid);
            let axial = master.u - spec.axial_start_col as i32;
            if axial < 0 || axial > spec.axial_squares as i32 {
                continue;
            }
            // The decode works in master-row units taken mod `p` -- that is
            // what lets `map_a` be used verbatim, since `3 | p` makes a row and
            // its reduction agree mod 3. The *public* index is measured from
            // the seam, so the start row comes off here, at the one boundary
            // where the two coordinates meet. Subtracting earlier would rotate
            // `map_a` by `start_row mod 3` and corrupt every vertical dot.
            let cyclic = (master.v - spec.start_row as i32).rem_euclid(period);
            out.push(PuzzlePoleCorner::new(
                spec,
                lc.position,
                axial as u32,
                cyclic as u32,
                lc.score,
            ));
        }

        // **Injectivity.** A wrapped pole cannot present a corner twice -- the
        // spare piece is glued under the first -- so two image positions
        // claiming one pole index means the target was not wrapped or the grid
        // was mislabelled. Refuse rather than pick one: a miss beats a wrong ID,
        // and nothing here can tell those two causes apart.
        let mut seen: Vec<(i32, i32)> = out.iter().map(|c| (c.grid.u, c.grid.v)).collect();
        seen.sort_unstable();
        if let Some(pair) = seen.windows(2).find(|w| w[0] == w[1]) {
            return Err(PuzzlePoleDetectError::InconsistentPosition {
                axial: pair[0].0 as u32,
                cyclic: pair[0].1 as u32,
            });
        }

        // **The window floor, in the pole's own axes.** Only now is it known
        // which way round the fragment sat: a patch 5 corners one way and 8 the
        // other decodes if the 8 runs along the axis and not if it runs around
        // the circumference, and nothing before the decode distinguishes those.
        let (circumference, axial) = pole_span(&out, period);
        if circumference < cfg.min_circumference_span || axial < cfg.min_axial_span {
            return Err(PuzzlePoleDetectError::FragmentTooSmall {
                circumference,
                axial,
                needed_circumference: cfg.min_circumference_span,
                needed_axial: cfg.min_axial_span,
            });
        }

        let matched = decoded.edges_matched;
        let info = PuzzleBoardDecodeInfo {
            edges_observed: decoded.edges_observed,
            edges_matched: matched,
            mean_confidence: decoded.mean_confidence,
            bit_error_rate: decoded.bit_error_rate,
            logical_bits: logical.len(),
            logical_bit_error_rate: decoded.bit_error_rate,
            dot_dissent_rate: consensus.dissent_rate(),
            master_origin_row: decoded.master_origin_row,
            master_origin_col: decoded.master_origin_col,
        };
        Ok(PuzzlePoleDetection::new(
            out,
            decoded.alignment,
            info,
            *spec,
        ))
    }
}

/// The corner spans a decoded fragment covers, as `(circumference, axial)`.
///
/// The axial span is an ordinary extent. The circumference one is **not**: the
/// indices live on a ring, so a fragment straddling the seam has indices at both
/// ends of the range and its bounding extent would read as nearly the whole
/// pole. The span is therefore the shortest arc containing every index — found
/// as the ring minus its largest gap, which is what "shortest containing arc"
/// means on a cycle.
fn pole_span(corners: &[PuzzlePoleCorner], period: i32) -> (u32, u32) {
    if corners.is_empty() {
        return (0, 0);
    }
    let axial_lo = corners.iter().map(|c| c.grid.u).min().unwrap_or(0);
    let axial_hi = corners.iter().map(|c| c.grid.u).max().unwrap_or(0);
    let axial = (axial_hi - axial_lo + 1) as u32;

    let mut used: Vec<i32> = corners
        .iter()
        .map(|c| c.grid.v.rem_euclid(period))
        .collect();
    used.sort_unstable();
    used.dedup();
    if used.len() as i32 >= period {
        return (period as u32, axial);
    }
    let largest_gap = used
        .windows(2)
        .map(|w| w[1] - w[0])
        .chain(std::iter::once(period - used[used.len() - 1] + used[0]))
        .max()
        .unwrap_or(period);
    ((period - largest_gap + 1) as u32, axial)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::PuzzlePoleSpec;
    use nalgebra::Point2;

    fn spec() -> PuzzlePoleSpec {
        PuzzlePoleSpec::new(12, 8, 20.0).expect("period 12 is supported")
    }

    fn corner_at(spec: &PuzzlePoleSpec, axial: u32, cyclic: u32) -> PuzzlePoleCorner {
        PuzzlePoleCorner::new(spec, Point2::new(0.0, 0.0), axial, cyclic, 1.0)
    }

    #[test]
    fn a_contiguous_fragment_spans_what_it_covers() {
        let spec = spec();
        let corners: Vec<_> = (2..7)
            .flat_map(|k| (1..4).map(move |a| (a, k)))
            .map(|(a, k)| corner_at(&spec, a, k))
            .collect();
        assert_eq!(pole_span(&corners, 12), (5, 3));
    }

    /// **The seam case.** Indices 10, 11, 0, 1 are four adjacent rows, not a
    /// fragment spanning almost the whole pole — which is what a bounding
    /// extent would call them, and which would pass a floor the fragment does
    /// not actually meet.
    #[test]
    fn a_fragment_across_the_seam_spans_the_short_arc() {
        let spec = spec();
        let corners: Vec<_> = [10u32, 11, 0, 1]
            .into_iter()
            .map(|k| corner_at(&spec, 2, k))
            .collect();
        assert_eq!(pole_span(&corners, 12).0, 4);
    }

    #[test]
    fn a_fragment_covering_the_whole_ring_spans_the_period() {
        let spec = spec();
        let corners: Vec<_> = (0..12).map(|k| corner_at(&spec, 2, k)).collect();
        assert_eq!(pole_span(&corners, 12).0, 12);
    }

    #[test]
    fn an_empty_fragment_spans_nothing() {
        assert_eq!(pole_span(&[], 12), (0, 0));
    }
}
