#ifndef CALIB_TARGETS_FFI_H
#define CALIB_TARGETS_FFI_H

#pragma once

/* Auto-generated by `cargo run -p calib-targets-ffi --bin generate-ffi-header`. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * ABI boolean false.
 */
#define CT_FALSE 0

/**
 * ABI boolean true.
 */
#define CT_TRUE 1

/**
 * Explicit status codes returned by all exported functions.
 */
typedef enum ct_status_t {
  CT_STATUS_OK = 0,
  CT_STATUS_NOT_FOUND = 1,
  CT_STATUS_INVALID_ARGUMENT = 2,
  CT_STATUS_BUFFER_TOO_SMALL = 3,
  CT_STATUS_CONFIG_ERROR = 4,
  CT_STATUS_INTERNAL_ERROR = 255,
} ct_status_t;

/**
 * Optional `uint32_t` convention used by fixed ABI structs.
 */
typedef struct ct_optional_u32_t {
  uint32_t has_value;
  uint32_t value;
} ct_optional_u32_t;

/**
 * Optional boolean convention used by fixed ABI structs.
 */
typedef struct ct_optional_bool_t {
  uint32_t has_value;
  uint32_t value;
} ct_optional_bool_t;

/**
 * Optional `float` convention used by fixed ABI structs.
 */
typedef struct ct_optional_f32_t {
  uint32_t has_value;
  float value;
} ct_optional_f32_t;

/**
 * Shared grayscale image descriptor for `u8` image input.
 *
 * `data` points to row-major pixels. `stride_bytes` may be greater than
 * `width` when rows are padded, but it must never be smaller than `width`.
 */
typedef struct ct_gray_image_u8_t {
  uint32_t width;
  uint32_t height;
  size_t stride_bytes;
  const uint8_t *data;
} ct_gray_image_u8_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the shared library version string.
 *
 * The returned pointer is static storage and must not be freed by the caller.
 */
const char *ct_version_string(void);

/**
 * Copy the most recent thread-local FFI error message into a caller-owned buffer.
 *
 * `out_len` is required and always receives the message length excluding the
 * trailing NUL terminator. Callers may query the required size by passing
 * `out_utf8 = NULL` and `out_capacity = 0`.
 * This function does not overwrite the stored thread-local error message if
 * the retrieval call itself fails.
 *
 * # Safety
 *
 * If `out_utf8` is non-null, it must point to writable memory of at least
 * `out_capacity` bytes. `out_len` must always be a valid writable pointer.
 */
enum ct_status_t ct_last_error_message(char *out_utf8, size_t out_capacity, size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CALIB_TARGETS_FFI_H */
