#ifndef CALIB_TARGETS_FFI_H
#define CALIB_TARGETS_FFI_H

#pragma once

/* Auto-generated by `cargo run -p calib-targets-ffi --bin generate-ffi-header`. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

/**
 * ABI boolean false.
 */
#define CT_FALSE 0

/**
 * ABI boolean true.
 */
#define CT_TRUE 1

/**
 * Explicit status codes returned by exported functions.
 */
typedef enum ct_status_t {
  CT_STATUS_OK = 0,
  CT_STATUS_NOT_FOUND = 1,
  CT_STATUS_INVALID_ARGUMENT = 2,
  CT_STATUS_BUFFER_TOO_SMALL = 3,
  CT_STATUS_CONFIG_ERROR = 4,
  CT_STATUS_INTERNAL_ERROR = 255,
} ct_status_t;

/**
 * Opaque ChArUco detector handle.
 */
typedef struct ct_charuco_detector_t ct_charuco_detector_t;

/**
 * Opaque chessboard detector handle.
 */
typedef struct ct_chessboard_detector_t ct_chessboard_detector_t;

/**
 * Opaque marker-board detector handle.
 */
typedef struct ct_marker_board_detector_t ct_marker_board_detector_t;

/**
 * Opaque PuzzleBoard detector handle.
 */
typedef struct ct_puzzleboard_detector_t ct_puzzleboard_detector_t;

/**
 * Selector for the chessboard graph-build algorithm. Mirrors the
 * `calib_targets_chessboard::GraphBuildAlgorithm` enum.
 *
 * Defaulting `ct_chessboard_params_t::graph_build_algorithm` to `0`
 * keeps zero-initialised C structs on the historical seed-and-grow
 * pipeline (`CT_GRAPH_BUILD_ALGORITHM_CHESSBOARD_V2`).
 */
typedef uint32_t ct_graph_build_algorithm_t;

/**
 * Opt-in, **unstable** per-stage tuning knobs for the chessboard detector.
 *
 * Mirrors the subset of `calib_targets::chessboard::AdvancedTuning` exposed
 * over the C ABI. Only applied when
 * [`ct_chessboard_params_t::has_advanced`] is `CT_TRUE`. These knobs are NOT
 * covered by semver and may change between minor versions; treat them as an
 * escape hatch for a specific failing input, not a stable contract.
 */
typedef struct ct_chessboard_advanced_t {
  float max_fit_rms_ratio;
  size_t num_bins;
  size_t max_iters_2means;
  float cluster_tol_deg;
  float peak_min_separation_deg;
  float min_peak_weight_fraction;
  float seed_edge_tol;
  float seed_axis_tol_deg;
  float seed_close_tol;
  float attach_search_rel;
  float attach_axis_tol_deg;
  float attach_ambiguity_factor;
  float step_tol;
  float edge_axis_tol_deg;
  float line_tol_rel;
  size_t line_min_members;
  float local_h_tol_rel;
  uint32_t max_validation_iters;
  uint32_t enable_weak_cluster_rescue;
  float weak_cluster_tol_deg;
  uint32_t max_booster_iters;
} ct_chessboard_advanced_t;

/**
 * Chessboard detector parameters.
 *
 * Mirrors `calib_targets::chessboard::DetectorParams` field-for-field
 * (flat shape — no nested graph / orientation-clustering sub-structs
 * like the pre-v0.7.0 ABI). Use `ct_chessboard_params_init_default`
 * to populate a valid default-configured value rather than struct-
 * literal zero-initialisation.
 */
typedef struct ct_chessboard_params_t {
  /**
   * Pipeline selector. See [`ct_graph_build_algorithm_t`].
   * Default `0` (== [`CT_GRAPH_BUILD_ALGORITHM_CHESSBOARD_V2`]).
   */
  ct_graph_build_algorithm_t graph_build_algorithm;
  /**
   * Minimum ChESS corner strength for the Stage-1 pre-filter. `0.0`
   * (the zero-initialised default) disables the filter. Stable field.
   */
  float min_corner_strength;
  /**
   * Minimum labelled corners for a detection to be emitted. Stable field.
   */
  size_t min_labeled_corners;
  /**
   * Maximum number of returned components. Stable field.
   */
  uint32_t max_components;
  /**
   * When `CT_TRUE`, the [`advanced`](Self::advanced) knobs below are
   * applied on top of the detector defaults. When `CT_FALSE` (the
   * zero-initialised default), `advanced` is ignored and the detector
   * runs on its precision-by-construction default tuning.
   *
   * The advanced knobs are NOT covered by semver and may change between
   * minor versions — see `calib_targets::chessboard::AdvancedTuning`.
   * Initialise from `ct_chessboard_params_default_values` before flipping
   * this flag so the advanced fields start from valid defaults.
   */
  uint32_t has_advanced;
  /**
   * Opt-in, unstable per-stage tuning. Only read when
   * [`has_advanced`](Self::has_advanced) is `CT_TRUE`.
   */
  struct ct_chessboard_advanced_t advanced;
} ct_chessboard_params_t;

/**
 * Optional boolean convention used by fixed ABI structs.
 */
typedef struct ct_optional_bool_t {
  uint32_t has_value;
  uint32_t value;
} ct_optional_bool_t;

/**
 * Optional `float` convention used by fixed ABI structs.
 */
typedef struct ct_optional_f32_t {
  uint32_t has_value;
  float value;
} ct_optional_f32_t;

/**
 * Fixed refiner identifier type for ChESS subpixel refinement.
 */
typedef uint32_t ct_refiner_kind_t;

/**
 * Center-of-mass refiner configuration.
 */
typedef struct ct_center_of_mass_config_t {
  int32_t radius;
} ct_center_of_mass_config_t;

/**
 * Förstner refiner configuration.
 */
typedef struct ct_forstner_config_t {
  int32_t radius;
  float min_trace;
  float min_det;
  float max_condition_number;
  float max_offset;
} ct_forstner_config_t;

/**
 * Saddle-point refiner configuration.
 */
typedef struct ct_saddle_point_config_t {
  int32_t radius;
  float det_margin;
  float max_offset;
  float min_abs_det;
} ct_saddle_point_config_t;

/**
 * ChESS refiner selection and parameters.
 */
typedef struct ct_refiner_config_t {
  ct_refiner_kind_t kind;
  struct ct_center_of_mass_config_t center_of_mass;
  struct ct_forstner_config_t forstner;
  struct ct_saddle_point_config_t saddle_point;
} ct_refiner_config_t;

/**
 * ChESS low-level detector parameters.
 */
typedef struct ct_chess_params_t {
  uint32_t use_radius10;
  struct ct_optional_bool_t descriptor_use_radius10;
  float threshold_rel;
  struct ct_optional_f32_t threshold_abs;
  uint32_t nms_radius;
  uint32_t min_cluster_size;
  struct ct_refiner_config_t refiner;
} ct_chess_params_t;

/**
 * ChESS pyramid configuration.
 */
typedef struct ct_pyramid_params_t {
  uint32_t num_levels;
  size_t min_size;
} ct_pyramid_params_t;

/**
 * Coarse-to-fine ChESS configuration.
 */
typedef struct ct_coarse_to_fine_params_t {
  struct ct_pyramid_params_t pyramid;
  uint32_t refinement_radius;
  float merge_radius;
} ct_coarse_to_fine_params_t;

/**
 * Fixed upscaling mode identifier type for ChESS pre-detection upscaling.
 */
typedef uint32_t ct_upscale_mode_t;

/**
 * Optional ChESS pre-detection upscaling configuration.
 */
typedef struct ct_upscale_config_t {
  ct_upscale_mode_t mode;
  uint32_t factor;
} ct_upscale_config_t;

/**
 * Shared ChESS configuration for raw corner detection.
 */
typedef struct ct_chess_config_t {
  struct ct_chess_params_t params;
  struct ct_coarse_to_fine_params_t multiscale;
  struct ct_upscale_config_t upscale;
} ct_chess_config_t;

/**
 * Full create-time configuration for the chessboard detector handle.
 */
typedef struct ct_chessboard_detector_config_t {
  struct ct_chess_config_t chess;
  struct ct_chessboard_params_t chessboard;
} ct_chessboard_detector_config_t;

/**
 * Shared grayscale image descriptor for `u8` image input.
 *
 * `data` points to row-major pixels. `stride_bytes` may be greater than
 * `width` when rows are padded, but it must never be smaller than `width`.
 */
typedef struct ct_gray_image_u8_t {
  uint32_t width;
  uint32_t height;
  size_t stride_bytes;
  const uint8_t *data;
} ct_gray_image_u8_t;

/**
 * Input arguments for [`ct_chessboard_detector_detect`].
 *
 * Groups the detector handle and image pointer so the entry point's
 * signature stays compact even as future fields are added.
 */
typedef struct ct_chessboard_detect_args_t {
  /**
   * Detector handle (from [`ct_chessboard_detector_create`]).
   */
  const struct ct_chessboard_detector_t *detector;
  /**
   * Grayscale image to scan.
   */
  const struct ct_gray_image_u8_t *image;
} ct_chessboard_detect_args_t;

/**
 * Chessboard detection header.
 *
 * Carries only the labelled-corner count; the corners themselves are
 * copied into the caller-provided `ct_chessboard_corner_t` array.
 */
typedef struct ct_chessboard_result_t {
  /**
   * Number of labelled corners in the detection.
   */
  size_t corners_len;
} ct_chessboard_result_t;

/**
 * Fixed 2D point output.
 */
typedef struct ct_point2f_t {
  float x;
  float y;
} ct_point2f_t;

/**
 * Fixed integer grid coordinate output.
 */
typedef struct ct_grid_coords_t {
  int32_t i;
  int32_t j;
} ct_grid_coords_t;

/**
 * One detected chessboard corner.
 *
 * A chessboard corner is always labelled, so `grid` is unconditional —
 * there is no `has_grid` flag. `input_index` is the index of the source
 * ChESS corner in the detector's input slice.
 */
typedef struct ct_chessboard_corner_t {
  /**
   * Sub-pixel image position.
   */
  struct ct_point2f_t position;
  /**
   * Grid label (i, j).
   */
  struct ct_grid_coords_t grid;
  /**
   * Index into the detector's input ChESS-corner slice.
   */
  size_t input_index;
  /**
   * Corner score.
   */
  float score;
} ct_chessboard_corner_t;

/**
 * Caller-provided output buffers for [`ct_chessboard_detector_detect`].
 *
 * `out_corners_len` is required and always receives the required number of
 * labelled-corner entries. Passing `out_corners = NULL` with
 * `corners_capacity = 0` queries the required length without copying
 * corner data.
 */
typedef struct ct_chessboard_detect_buffers_t {
  /**
   * Optional scalar result header. May be null.
   */
  struct ct_chessboard_result_t *out_result;
  /**
   * Output array of labelled chessboard corners. May be null when `corners_capacity = 0`.
   */
  struct ct_chessboard_corner_t *out_corners;
  size_t corners_capacity;
  /**
   * Required: always receives the number of corners detected.
   */
  size_t *out_corners_len;
} ct_chessboard_detect_buffers_t;

/**
 * Input arguments for [`ct_chessboard_detector_detect_all`].
 *
 * Groups the detector handle and image pointer so the entry point's
 * signature stays compact even as future fields are added.
 */
typedef struct ct_chessboard_detect_all_args_t {
  /**
   * Detector handle (from [`ct_chessboard_detector_create`]).
   */
  const struct ct_chessboard_detector_t *detector;
  /**
   * Grayscale image to scan.
   */
  const struct ct_gray_image_u8_t *image;
} ct_chessboard_detect_all_args_t;

/**
 * Caller-provided output buffers for [`ct_chessboard_detector_detect_all`].
 *
 * Each `*_buf` is the start of a writable output array, `*_capacity`
 * its allocated entry count, and `*_len_out` a writable destination
 * that receives the *required* number of entries (even if the buffer
 * is too small or null). Passing a `NULL` buffer with capacity `0` is
 * allowed and queries the required length without copying data.
 */
typedef struct ct_chessboard_detect_all_buffers_t {
  /**
   * Output array of per-component result headers.
   */
  struct ct_chessboard_result_t *results_buf;
  size_t results_capacity;
  size_t *results_len_out;
  /**
   * Output array of all components' labelled chessboard corners concatenated.
   */
  struct ct_chessboard_corner_t *corners_buf;
  size_t corners_capacity;
  size_t *corners_len_out;
} ct_chessboard_detect_all_buffers_t;

/**
 * Fixed dictionary identifier type for built-in marker dictionaries.
 */
typedef uint32_t ct_dictionary_id_t;

/**
 * Fixed board marker-layout identifier type.
 */
typedef uint32_t ct_marker_layout_t;

/**
 * ChArUco board specification.
 */
typedef struct ct_charuco_board_spec_t {
  uint32_t rows;
  uint32_t cols;
  float cell_size;
  float marker_size_rel;
  ct_dictionary_id_t dictionary;
  ct_marker_layout_t marker_layout;
} ct_charuco_board_spec_t;

/**
 * Marker scan/decode configuration.
 */
typedef struct ct_scan_decode_config_t {
  size_t border_bits;
  float inset_frac;
  float marker_size_rel;
  float min_border_score;
  uint32_t dedup_by_id;
  /**
   * If `CT_TRUE`, try multiple thresholds per cell before giving up.
   */
  uint32_t multi_threshold;
} ct_scan_decode_config_t;

/**
 * ChArUco detector parameters.
 */
typedef struct ct_charuco_detector_params_t {
  float px_per_square;
  struct ct_chessboard_params_t chessboard;
  struct ct_charuco_board_spec_t charuco;
  struct ct_scan_decode_config_t scan;
  uint32_t max_hamming;
  size_t min_marker_inliers;
  float grid_smoothness_threshold_rel;
  float corner_validation_threshold_rel;
  struct ct_chess_params_t corner_redetect_params;
} ct_charuco_detector_params_t;

/**
 * Full create-time configuration for the ChArUco detector handle.
 */
typedef struct ct_charuco_detector_config_t {
  struct ct_chess_config_t chess;
  struct ct_charuco_detector_params_t detector;
} ct_charuco_detector_config_t;

/**
 * Input arguments for [`ct_charuco_detector_detect`].
 *
 * Groups the detector handle and image pointer so the entry point's
 * signature stays compact even as future fields are added.
 */
typedef struct ct_charuco_detect_args_t {
  /**
   * Detector handle (from [`ct_charuco_detector_create`]).
   */
  const struct ct_charuco_detector_t *detector;
  /**
   * Grayscale image to scan.
   */
  const struct ct_gray_image_u8_t *image;
} ct_charuco_detect_args_t;

/**
 * Fixed target kind identifier type.
 */
typedef uint32_t ct_target_kind_t;

/**
 * Shared target-detection header.
 */
typedef struct ct_target_detection_t {
  ct_target_kind_t kind;
  size_t corners_len;
} ct_target_detection_t;

/**
 * Fixed integer grid transform output.
 */
typedef struct ct_grid_transform_t {
  int32_t a;
  int32_t b;
  int32_t c;
  int32_t d;
} ct_grid_transform_t;

/**
 * Fixed integer grid alignment output.
 */
typedef struct ct_grid_alignment_t {
  struct ct_grid_transform_t transform;
  int32_t translation_i;
  int32_t translation_j;
} ct_grid_alignment_t;

/**
 * ChArUco detection header.
 */
typedef struct ct_charuco_result_t {
  struct ct_target_detection_t detection;
  size_t markers_len;
  struct ct_grid_alignment_t alignment;
} ct_charuco_result_t;

/**
 * Optional `uint32_t` convention used by fixed ABI structs.
 */
typedef struct ct_optional_u32_t {
  uint32_t has_value;
  uint32_t value;
} ct_optional_u32_t;

/**
 * One detected labeled corner.
 */
typedef struct ct_labeled_corner_t {
  struct ct_point2f_t position;
  uint32_t has_grid;
  struct ct_grid_coords_t grid;
  struct ct_optional_u32_t id;
  uint32_t has_target_position;
  struct ct_point2f_t target_position;
  float score;
} ct_labeled_corner_t;

/**
 * One decoded marker detection.
 */
typedef struct ct_marker_detection_t {
  uint32_t id;
  struct ct_grid_coords_t grid_cell;
  uint8_t rotation;
  uint8_t hamming;
  uint8_t _reserved0[2];
  float score;
  float border_score;
  uint64_t code;
  uint32_t inverted;
  struct ct_point2f_t corners_rect[4];
  uint32_t has_corners_img;
  struct ct_point2f_t corners_img[4];
} ct_marker_detection_t;

/**
 * Caller-provided output buffers for [`ct_charuco_detector_detect`].
 *
 * `out_corners_len` and `out_markers_len` are required and always receive
 * the required array lengths. Passing a `NULL` output array with
 * `*_capacity = 0` queries the required length without copying array data.
 */
typedef struct ct_charuco_detect_buffers_t {
  /**
   * Optional scalar result header. May be null.
   */
  struct ct_charuco_result_t *out_result;
  /**
   * Output array of labelled corners. May be null when `corners_capacity = 0`.
   */
  struct ct_labeled_corner_t *out_corners;
  size_t corners_capacity;
  /**
   * Required: always receives the number of corners detected.
   */
  size_t *out_corners_len;
  /**
   * Output array of decoded marker detections. May be null when `markers_capacity = 0`.
   */
  struct ct_marker_detection_t *out_markers;
  size_t markers_capacity;
  /**
   * Required: always receives the number of markers detected.
   */
  size_t *out_markers_len;
} ct_charuco_detect_buffers_t;

/**
 * Fixed circle polarity identifier type.
 */
typedef uint32_t ct_circle_polarity_t;

/**
 * One expected marker circle on the board.
 */
typedef struct ct_marker_circle_spec_t {
  struct ct_grid_coords_t cell;
  ct_circle_polarity_t polarity;
} ct_marker_circle_spec_t;

/**
 * Fixed marker-board layout.
 */
typedef struct ct_marker_board_layout_t {
  uint32_t rows;
  uint32_t cols;
  struct ct_optional_f32_t cell_size;
  struct ct_marker_circle_spec_t circles[3];
} ct_marker_board_layout_t;

/**
 * Circle-score parameters for marker-board detection.
 */
typedef struct ct_circle_score_params_t {
  size_t patch_size;
  float diameter_frac;
  float ring_thickness_frac;
  float ring_radius_mul;
  float min_contrast;
  size_t samples;
  int32_t center_search_px;
} ct_circle_score_params_t;

/**
 * Circle-match parameters for marker-board detection.
 */
typedef struct ct_circle_match_params_t {
  size_t max_candidates_per_polarity;
  struct ct_optional_f32_t max_distance_cells;
  size_t min_offset_inliers;
} ct_circle_match_params_t;

/**
 * Marker-board detector parameters.
 */
typedef struct ct_marker_board_params_t {
  struct ct_marker_board_layout_t layout;
  struct ct_chessboard_params_t chessboard;
  struct ct_circle_score_params_t circle_score;
  struct ct_circle_match_params_t match_params;
  uint32_t has_roi_cells;
  int32_t roi_cells[4];
} ct_marker_board_params_t;

/**
 * Full create-time configuration for the marker-board detector handle.
 */
typedef struct ct_marker_board_detector_config_t {
  struct ct_chess_config_t chess;
  struct ct_marker_board_params_t detector;
} ct_marker_board_detector_config_t;

/**
 * Input arguments for [`ct_marker_board_detector_detect`].
 *
 * Groups the detector handle and image pointer so the entry point's
 * signature stays compact even as future fields are added.
 */
typedef struct ct_marker_board_detect_args_t {
  /**
   * Detector handle (from [`ct_marker_board_detector_create`]).
   */
  const struct ct_marker_board_detector_t *detector;
  /**
   * Grayscale image to scan.
   */
  const struct ct_gray_image_u8_t *image;
} ct_marker_board_detect_args_t;

/**
 * Marker-board detection header.
 *
 * Carries the facts a consumer needs to *use* a marker-board detection:
 * the labelled-corner header and the optional grid alignment. Detection
 * evidence (every scored circle hypothesis, the expected-to-detected
 * circle pairings, the per-corner provenance, the alignment-inlier count)
 * is intentionally not surfaced over the C ABI — it is the Rust
 * `MarkerBoardDiagnostics` channel, which has no FFI binding.
 */
typedef struct ct_marker_board_result_t {
  struct ct_target_detection_t detection;
  uint32_t has_alignment;
  struct ct_grid_alignment_t alignment;
} ct_marker_board_result_t;

/**
 * Caller-provided output buffers for [`ct_marker_board_detector_detect`].
 *
 * `out_corners_len` is required and always receives the required number of
 * labelled-corner entries. Passing `out_corners = NULL` with
 * `corners_capacity = 0` queries the required length without copying
 * corner data. Detection evidence (scored circle hypotheses, circle
 * matches) is not surfaced over the C ABI — see
 * [`ct_marker_board_result_t`].
 */
typedef struct ct_marker_board_detect_buffers_t {
  /**
   * Optional scalar result header. May be null.
   */
  struct ct_marker_board_result_t *out_result;
  /**
   * Output array of labelled corners. May be null when `corners_capacity = 0`.
   */
  struct ct_labeled_corner_t *out_corners;
  size_t corners_capacity;
  /**
   * Required: always receives the number of corners detected.
   */
  size_t *out_corners_len;
} ct_marker_board_detect_buffers_t;

/**
 * PuzzleBoard board specification.
 */
typedef struct ct_puzzleboard_spec_t {
  uint32_t rows;
  uint32_t cols;
  float cell_size;
  uint32_t origin_row;
  uint32_t origin_col;
} ct_puzzleboard_spec_t;

/**
 * Fixed PuzzleBoard search-mode identifier type.
 */
typedef uint32_t ct_puzzleboard_search_mode_t;

/**
 * Fixed PuzzleBoard scoring-mode identifier type.
 */
typedef uint32_t ct_puzzleboard_scoring_mode_t;

/**
 * PuzzleBoard edge-bit decode parameters.
 */
typedef struct ct_puzzleboard_decode_config_t {
  uint32_t min_window;
  float min_bit_confidence;
  float max_bit_error_rate;
  uint32_t search_all_components;
  float sample_radius_rel;
  ct_puzzleboard_search_mode_t search_mode;
  ct_puzzleboard_scoring_mode_t scoring_mode;
  float bit_likelihood_slope;
  float per_bit_floor;
  float alignment_min_margin;
} ct_puzzleboard_decode_config_t;

/**
 * PuzzleBoard detector parameters.
 */
typedef struct ct_puzzleboard_params_t {
  float px_per_square;
  struct ct_chessboard_params_t chessboard;
  struct ct_puzzleboard_spec_t board;
  struct ct_puzzleboard_decode_config_t decode;
  struct ct_chess_params_t corner_redetect_params;
} ct_puzzleboard_params_t;

/**
 * Full create-time configuration for the PuzzleBoard detector handle.
 */
typedef struct ct_puzzleboard_detector_config_t {
  struct ct_chess_config_t chess;
  struct ct_puzzleboard_params_t detector;
} ct_puzzleboard_detector_config_t;

/**
 * Input arguments for [`ct_puzzleboard_detector_detect`].
 *
 * Groups the detector handle and image pointer so the entry point's
 * signature stays compact even as future fields are added.
 */
typedef struct ct_puzzleboard_detect_args_t {
  /**
   * Detector handle (from [`ct_puzzleboard_detector_create`]).
   */
  const struct ct_puzzleboard_detector_t *detector;
  /**
   * Grayscale image to scan.
   */
  const struct ct_gray_image_u8_t *image;
} ct_puzzleboard_detect_args_t;

/**
 * PuzzleBoard detection header and compact decode quality summary.
 *
 * Carries the facts a consumer needs to *use* a PuzzleBoard detection.
 * Decode-internal evidence (winner/runner-up scores, the raw per-edge
 * observation dump) is intentionally not surfaced over the C ABI — it is
 * the Rust `PuzzleBoardDiagnostics` channel, which has no FFI binding.
 */
typedef struct ct_puzzleboard_result_t {
  struct ct_target_detection_t detection;
  struct ct_grid_alignment_t alignment;
  size_t edges_observed;
  size_t edges_matched;
  float mean_bit_confidence;
  float bit_error_rate;
  int32_t master_origin_row;
  int32_t master_origin_col;
} ct_puzzleboard_result_t;

/**
 * Caller-provided output buffers for [`ct_puzzleboard_detector_detect`].
 *
 * `out_corners_len` is required and always receives the required number of
 * labeled-corner entries. Passing `out_corners = NULL` with
 * `corners_capacity = 0` queries the required length without copying
 * corner data. The returned corner grid coordinates are master-board
 * `(I, J)` labels.
 */
typedef struct ct_puzzleboard_detect_buffers_t {
  /**
   * Optional scalar result header. May be null.
   */
  struct ct_puzzleboard_result_t *out_result;
  /**
   * Output array of labelled corners. May be null when `corners_capacity = 0`.
   */
  struct ct_labeled_corner_t *out_corners;
  size_t corners_capacity;
  /**
   * Required: always receives the number of corners detected.
   */
  size_t *out_corners_len;
} ct_puzzleboard_detect_buffers_t;

/**
 * Seed-and-grow pipeline. Currently the default.
 */
#define CT_GRAPH_BUILD_ALGORITHM_CHESSBOARD_V2 0

/**
 * Topological pipeline (Delaunay + axis-driven cell test).
 */
#define CT_GRAPH_BUILD_ALGORITHM_TOPOLOGICAL 1

#define CT_DICTIONARY_DICT_4X4_50 1

#define CT_DICTIONARY_DICT_4X4_100 2

#define CT_DICTIONARY_DICT_4X4_250 3

#define CT_DICTIONARY_DICT_4X4_1000 4

#define CT_DICTIONARY_DICT_5X5_50 5

#define CT_DICTIONARY_DICT_5X5_100 6

#define CT_DICTIONARY_DICT_5X5_250 7

#define CT_DICTIONARY_DICT_5X5_1000 8

#define CT_DICTIONARY_DICT_6X6_50 9

#define CT_DICTIONARY_DICT_6X6_100 10

#define CT_DICTIONARY_DICT_6X6_250 11

#define CT_DICTIONARY_DICT_6X6_1000 12

#define CT_DICTIONARY_DICT_7X7_50 13

#define CT_DICTIONARY_DICT_7X7_100 14

#define CT_DICTIONARY_DICT_7X7_250 15

#define CT_DICTIONARY_DICT_7X7_1000 16

#define CT_DICTIONARY_DICT_APRILTAG_16H5 17

#define CT_DICTIONARY_DICT_APRILTAG_25H9 18

#define CT_DICTIONARY_DICT_APRILTAG_36H10 19

#define CT_DICTIONARY_DICT_APRILTAG_36H11 20

#define CT_DICTIONARY_DICT_ARUCO_MIP_36H12 21

#define CT_DICTIONARY_DICT_ARUCO_ORIGINAL 22

#define CT_REFINER_KIND_CENTER_OF_MASS 1

#define CT_REFINER_KIND_FORSTNER 2

#define CT_REFINER_KIND_SADDLE_POINT 3

#define CT_UPSCALE_MODE_DISABLED 0

#define CT_UPSCALE_MODE_FIXED 1

#define CT_MARKER_LAYOUT_OPENCV_CHARUCO 1

#define CT_TARGET_KIND_CHESSBOARD 1

#define CT_TARGET_KIND_CHARUCO 2

#define CT_TARGET_KIND_CHECKERBOARD_MARKER 3

#define CT_TARGET_KIND_PUZZLEBOARD 4

#define CT_PUZZLEBOARD_SEARCH_MODE_FULL 1

#define CT_PUZZLEBOARD_SEARCH_MODE_FIXED_BOARD 2

#define CT_PUZZLEBOARD_SCORING_MODE_HARD_WEIGHTED 1

#define CT_PUZZLEBOARD_SCORING_MODE_SOFT_LOG_LIKELIHOOD 2

#define CT_CIRCLE_POLARITY_WHITE 1

#define CT_CIRCLE_POLARITY_BLACK 2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the shared library version string.
 *
 * The returned pointer is static storage and must not be freed by the caller.
 */
const char *ct_version_string(void);

/**
 * Copy the most recent thread-local FFI error message into a caller-owned buffer.
 *
 * `out_len` is required and always receives the message length excluding the
 * trailing NUL terminator. Callers may query the required size by passing
 * `out_utf8 = NULL` and `out_capacity = 0`.
 * This function does not overwrite the stored thread-local error message if
 * the retrieval call itself fails.
 *
 * # Safety
 *
 * If `out_utf8` is non-null, it must point to writable memory of at least
 * `out_capacity` bytes. `out_len` must always be a valid writable pointer.
 */
enum ct_status_t ct_last_error_message(char *out_utf8, size_t out_capacity, size_t *out_len);

/**
 * Return a `ct_chessboard_params_t` populated from
 * `DetectorParams::default()`. Exposed as a C symbol so callers don't
 * need to hand-fill 30+ fields.
 * # Safety
 * `out` must be a valid, properly aligned pointer to a writable
 * `ct_chessboard_params_t` storage location. `NULL` is allowed and
 * is a no-op. The caller retains ownership of the storage.
 */
void ct_chessboard_params_init_default(struct ct_chessboard_params_t *out);

/**
 * Create a chessboard detector handle.
 *
 * # Safety
 *
 * `config` and `out_detector` must be valid non-null pointers. On success,
 * `*out_detector` receives a new handle owned by the caller.
 */
enum ct_status_t ct_chessboard_detector_create(const struct ct_chessboard_detector_config_t *config,
                                               struct ct_chessboard_detector_t **out_detector);

/**
 * Destroy a chessboard detector handle.
 *
 * Passing `NULL` is allowed and has no effect.
 *
 * # Safety
 *
 * `detector` must either be null or a handle returned by
 * [`ct_chessboard_detector_create`] that has not already been destroyed.
 */
void ct_chessboard_detector_destroy(struct ct_chessboard_detector_t *detector);

/**
 * Run end-to-end chessboard detection on a grayscale image.
 *
 * `bufs.out_corners_len` is required and always receives the required number
 * of `ct_chessboard_corner_t` entries. Passing `bufs.out_corners = NULL` and
 * `bufs.corners_capacity = 0` queries the required length without copying
 * corner data.
 *
 * # Safety
 *
 * `args` and `bufs` must be valid non-null pointers to populated struct
 * instances. Inside `args`: `detector` and `image` must be valid non-null
 * pointers. Inside `bufs`: `out_corners_len` must be a valid non-null
 * writable pointer; `out_result` may be null; `out_corners` may be null
 * when `corners_capacity = 0`, otherwise it must point to writable storage
 * of at least `corners_capacity` entries.
 */
enum ct_status_t ct_chessboard_detector_detect(const struct ct_chessboard_detect_args_t *args,
                                               struct ct_chessboard_detect_buffers_t *bufs);

/**
 * Run chessboard detection and write the diagnostics channel as a
 * NUL-terminated UTF-8 JSON string into a caller-owned buffer.
 *
 * The JSON payload is `serde_json::to_string` of the Rust `DebugFrame`
 * diagnostics struct (every input corner's terminal stage, per-iteration
 * pipeline traces, cluster histograms, geometry-check outcomes). Its
 * schema carries a looser stability promise than the typed result API and
 * may evolve between minor versions.
 *
 * `out_len` is required and always receives the JSON length excluding the
 * trailing NUL terminator. Query the required size by passing
 * `out_utf8 = NULL` and `out_capacity = 0`.
 *
 * # Safety
 *
 * `args` must be a valid non-null pointer whose `detector` and `image`
 * fields are valid non-null pointers. If `out_utf8` is non-null it must
 * point to writable memory of at least `out_capacity` bytes. `out_len`
 * must always be a valid writable pointer.
 */
enum ct_status_t ct_chessboard_detector_detect_diagnostics_json(const struct ct_chessboard_detect_args_t *args,
                                                                char *out_utf8,
                                                                size_t out_capacity,
                                                                size_t *out_len);

/**
 * Run end-to-end multi-component chessboard detection on a grayscale image.
 *
 * Returns every same-board component the detector recovers, up to
 * `DetectorParams::max_components`. The `corners_buf` buffer receives
 * all corners from all components concatenated; use
 * `result[i].corners_len` to slice each component's contribution.
 *
 * Both `results_len_out` and `corners_len_out` inside `bufs` are
 * required and always receive the required array lengths. Passing
 * `NULL` output buffers with capacity `0` queries the required
 * lengths without copying data.
 *
 * # Safety
 *
 * `args` and `bufs` must be valid non-null pointers to populated
 * struct instances. Inside `args`: `detector` and `image` must be
 * valid non-null pointers. Inside `bufs`: `results_len_out` and
 * `corners_len_out` must be valid non-null writable pointers; each
 * output array buffer is allowed to be null when its capacity is `0`,
 * otherwise it must point to writable storage of at least the
 * declared capacity.
 */
enum ct_status_t ct_chessboard_detector_detect_all(const struct ct_chessboard_detect_all_args_t *args,
                                                   struct ct_chessboard_detect_all_buffers_t *bufs);

/**
 * Create a ChArUco detector handle.
 *
 * # Safety
 *
 * `config` and `out_detector` must be valid non-null pointers. On success,
 * `*out_detector` receives a new handle owned by the caller.
 */
enum ct_status_t ct_charuco_detector_create(const struct ct_charuco_detector_config_t *config,
                                            struct ct_charuco_detector_t **out_detector);

/**
 * Destroy a ChArUco detector handle.
 *
 * Passing `NULL` is allowed and has no effect.
 *
 * # Safety
 *
 * `detector` must either be null or a handle returned by
 * [`ct_charuco_detector_create`] that has not already been destroyed.
 */
void ct_charuco_detector_destroy(struct ct_charuco_detector_t *detector);

/**
 * Run end-to-end ChArUco detection on a grayscale image.
 *
 * `bufs.out_corners_len` and `bufs.out_markers_len` are required and always
 * receive the required array lengths. Passing a `NULL` output array with
 * `*_capacity = 0` queries the required length without copying array data.
 *
 * # Safety
 *
 * `args` and `bufs` must be valid non-null pointers to populated struct
 * instances. Inside `args`: `detector` and `image` must be valid non-null
 * pointers. Inside `bufs`: `out_corners_len` and `out_markers_len` must be
 * valid non-null writable pointers; `out_result` may be null; each array
 * buffer may be null when its capacity is `0`, otherwise it must point to
 * writable storage of at least the declared capacity.
 */
enum ct_status_t ct_charuco_detector_detect(const struct ct_charuco_detect_args_t *args,
                                            struct ct_charuco_detect_buffers_t *bufs);

/**
 * Run ChArUco detection and write the diagnostics channel as a
 * NUL-terminated UTF-8 JSON string into a caller-owned buffer.
 *
 * The JSON payload is `serde_json::to_string` of the Rust
 * `CharucoDetectDiagnostics` struct (per-component matcher decisions,
 * per-cell scores, chosen/runner-up hypotheses, rejection reasons).
 * Diagnostics are produced even when detection fails, so this entry point
 * returns `CT_STATUS_OK` with a well-formed payload on failed frames; its
 * schema carries a looser stability promise than the typed result API.
 *
 * `out_len` is required and always receives the JSON length excluding the
 * trailing NUL terminator. Query the required size by passing
 * `out_utf8 = NULL` and `out_capacity = 0`.
 *
 * # Safety
 *
 * `args` must be a valid non-null pointer whose `detector` and `image`
 * fields are valid non-null pointers. If `out_utf8` is non-null it must
 * point to writable memory of at least `out_capacity` bytes. `out_len`
 * must always be a valid writable pointer.
 */
enum ct_status_t ct_charuco_detector_detect_diagnostics_json(const struct ct_charuco_detect_args_t *args,
                                                             char *out_utf8,
                                                             size_t out_capacity,
                                                             size_t *out_len);

/**
 * Create a marker-board detector handle.
 *
 * # Safety
 *
 * `config` and `out_detector` must be valid non-null pointers. On success,
 * `*out_detector` receives a new handle owned by the caller.
 */
enum ct_status_t ct_marker_board_detector_create(const struct ct_marker_board_detector_config_t *config,
                                                 struct ct_marker_board_detector_t **out_detector);

/**
 * Destroy a marker-board detector handle.
 *
 * Passing `NULL` is allowed and has no effect.
 *
 * # Safety
 *
 * `detector` must either be null or a handle returned by
 * [`ct_marker_board_detector_create`] that has not already been destroyed.
 */
void ct_marker_board_detector_destroy(struct ct_marker_board_detector_t *detector);

/**
 * Run end-to-end marker-board detection on a grayscale image.
 *
 * The three `*_len` pointers inside `bufs` are required and always receive
 * the required lengths for the corresponding output arrays. Passing a `NULL`
 * output array with `*_capacity = 0` queries the required length without
 * copying array data.
 *
 * # Safety
 *
 * `args` and `bufs` must be valid non-null pointers to populated struct
 * instances. Inside `args`: `detector` and `image` must be valid non-null
 * pointers. Inside `bufs`: all three `*_len` pointers must be valid non-null
 * writable pointers; `out_result` may be null; each array buffer may be null
 * when its capacity is `0`, otherwise it must point to writable storage of
 * at least the declared capacity.
 */
enum ct_status_t ct_marker_board_detector_detect(const struct ct_marker_board_detect_args_t *args,
                                                 struct ct_marker_board_detect_buffers_t *bufs);

/**
 * Run marker-board detection and write the diagnostics channel as a
 * NUL-terminated UTF-8 JSON string into a caller-owned buffer.
 *
 * The JSON payload is `serde_json::to_string` of the Rust
 * `MarkerBoardDiagnostics` struct (every scored circle hypothesis, the
 * expected-to-detected circle matches, per-corner provenance, and the
 * alignment-inlier count). The marker-board diagnostics channel only
 * yields evidence on a successful detection, so a failed detection is
 * reported as `CT_STATUS_NOT_FOUND`; its schema carries a looser
 * stability promise than the typed result API.
 *
 * `out_len` is required and always receives the JSON length excluding the
 * trailing NUL terminator. Query the required size by passing
 * `out_utf8 = NULL` and `out_capacity = 0`.
 *
 * # Safety
 *
 * `args` must be a valid non-null pointer whose `detector` and `image`
 * fields are valid non-null pointers. If `out_utf8` is non-null it must
 * point to writable memory of at least `out_capacity` bytes. `out_len`
 * must always be a valid writable pointer.
 */
enum ct_status_t ct_marker_board_detector_detect_diagnostics_json(const struct ct_marker_board_detect_args_t *args,
                                                                  char *out_utf8,
                                                                  size_t out_capacity,
                                                                  size_t *out_len);

/**
 * Create a PuzzleBoard detector handle.
 *
 * # Safety
 *
 * `config` and `out_detector` must be valid non-null pointers. On success,
 * `*out_detector` receives a new handle owned by the caller.
 */
enum ct_status_t ct_puzzleboard_detector_create(const struct ct_puzzleboard_detector_config_t *config,
                                                struct ct_puzzleboard_detector_t **out_detector);

/**
 * Destroy a PuzzleBoard detector handle.
 *
 * Passing `NULL` is allowed and has no effect.
 *
 * # Safety
 *
 * `detector` must either be null or a handle returned by
 * [`ct_puzzleboard_detector_create`] that has not already been destroyed.
 */
void ct_puzzleboard_detector_destroy(struct ct_puzzleboard_detector_t *detector);

/**
 * Run end-to-end PuzzleBoard detection on a grayscale image.
 *
 * `bufs.out_corners_len` is required and always receives the required number
 * of labeled-corner entries. Passing `bufs.out_corners = NULL` with
 * `bufs.corners_capacity = 0` queries the required length without copying
 * corner data. The returned corner grid coordinates are master-board
 * `(I, J)` labels.
 *
 * # Safety
 *
 * `args` and `bufs` must be valid non-null pointers to populated struct
 * instances. Inside `args`: `detector` and `image` must be valid non-null
 * pointers. Inside `bufs`: `out_corners_len` must be a valid non-null
 * writable pointer; `out_result` may be null; `out_corners` may be null
 * when `corners_capacity = 0`, otherwise it must point to writable storage
 * of at least `corners_capacity` entries.
 */
enum ct_status_t ct_puzzleboard_detector_detect(const struct ct_puzzleboard_detect_args_t *args,
                                                struct ct_puzzleboard_detect_buffers_t *bufs);

/**
 * Run PuzzleBoard detection and write the diagnostics channel as a
 * NUL-terminated UTF-8 JSON string into a caller-owned buffer.
 *
 * The JSON payload is `serde_json::to_string` of the Rust
 * `PuzzleBoardDiagnostics` struct (the raw pre-alignment per-edge bit
 * observations and the winner-vs-runner-up scoring evidence). Diagnostics
 * are produced even when detection fails, so this entry point returns
 * `CT_STATUS_OK` with a well-formed payload on failed frames; its schema
 * carries a looser stability promise than the typed result API.
 *
 * `out_len` is required and always receives the JSON length excluding the
 * trailing NUL terminator. Query the required size by passing
 * `out_utf8 = NULL` and `out_capacity = 0`.
 *
 * # Safety
 *
 * `args` must be a valid non-null pointer whose `detector` and `image`
 * fields are valid non-null pointers. If `out_utf8` is non-null it must
 * point to writable memory of at least `out_capacity` bytes. `out_len`
 * must always be a valid writable pointer.
 */
enum ct_status_t ct_puzzleboard_detector_detect_diagnostics_json(const struct ct_puzzleboard_detect_args_t *args,
                                                                 char *out_utf8,
                                                                 size_t out_capacity,
                                                                 size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CALIB_TARGETS_FFI_H */
